# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/iyokan/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/semc/iyokan/proprietary/lib/libcamera.so:obj/lib/libcamera.so

PRODUCT_COPY_FILES += \
    vendor/semc/iyokan/proprietary//system/usr/keychars/qwerty.kcm.bin:system//system/usr/keychars/qwerty.kcm.bin \
    vendor/semc/iyokan/proprietary//system/usr/keychars/qwerty.kcm.bin:system//system/usr/keychars/qwerty.kcm.bin \
    vendor/semc/iyokan/proprietary//system/usr/keychars/qwerty2.kcm.bin:system//system/usr/keychars/qwerty2.kcm.bin \
    vendor/semc/iyokan/proprietary//system/usr/keylayout/atdaemon.kl:system//system/usr/keylayout/atdaemon.kl \
    vendor/semc/iyokan/proprietary//system/usr/keylayout/AVRCP.kl:system//system/usr/keylayout/AVRCP.kl \
    vendor/semc/iyokan/proprietary//system/usr/keylayout/msm_pmic_pwr_key.kl:system//system/usr/keylayout/msm_pmic_pwr_key.kl \
    vendor/semc/iyokan/proprietary//system/usr/keylayout/pm8058-keypad.kl:system//system/usr/keylayout/pm8058-keypad.kl \
    vendor/semc/iyokan/proprietary//system/usr/keylayout/qwerty.kl:system//system/usr/keylayout/qwerty.kl \
    vendor/semc/iyokan/proprietary//system/usr/keylayout/simple_remote.kl:system//system/usr/keylayout/simple_remote.kl \
    vendor/semc/iyokan/proprietary//system/usr/keychars/us104-keyboard.kcm.bin:system//system/usr/keychars/us104-keyboard.kcm.bin \
    vendor/semc/iyokan/proprietary//system/usr/keylayout/us104-keyboard.kl:system//system/usr/keylayout/us104-keyboard.kl \
    vendor/semc/iyokan/proprietary//system/usr/keylayout/usb_mouse.kl:system//system/usr/keylayout/usb_mouse.kl \
    vendor/semc/iyokan/proprietary//system/bin/port-bridge:system//system/bin/port-bridge \
    vendor/semc/iyokan/proprietary//system/bin/qmuxd:system//system/bin/qmuxd \
    vendor/semc/iyokan/proprietary//system/lib/libril.so:system//system/lib/libril.so \
    vendor/semc/iyokan/proprietary//system/lib/libauth.so:system//system/lib/libauth.so \
    vendor/semc/iyokan/proprietary//system/lib/libcm.so:system//system/lib/libcm.so \
    vendor/semc/iyokan/proprietary//system/lib/libdiag.so:system//system/lib/libdiag.so \
    vendor/semc/iyokan/proprietary//system/lib/libdll.so:system//system/lib/libdll.so \
    vendor/semc/iyokan/proprietary//system/lib/libdsm.so:system//system/lib/libdsm.so \
    vendor/semc/iyokan/proprietary//system/lib/libdss.so:system//system/lib/libdss.so \
    vendor/semc/iyokan/proprietary//system/lib/libgsdi_exp.so:system//system/lib/libgsdi_exp.so \
    vendor/semc/iyokan/proprietary//system/lib/libgstk_exp.so:system//system/lib/libgstk_exp.so \
    vendor/semc/iyokan/proprietary//system/lib/libmmgsdilib.so:system//system/lib/libmmgsdilib.so \
    vendor/semc/iyokan/proprietary//system/lib/libnv.so:system//system/lib/libnv.so \
    vendor/semc/iyokan/proprietary//system/lib/liboem_rapi.so:system//system/lib/liboem_rapi.so \
    vendor/semc/iyokan/proprietary//system/lib/liboncrpc.so:system//system/lib/liboncrpc.so \
    vendor/semc/iyokan/proprietary//system/lib/libpbmlib.so:system//system/lib/libpbmlib.so \
    vendor/semc/iyokan/proprietary//system/lib/libqmi.so:system//system/lib/libqmi.so \
    vendor/semc/iyokan/proprietary//system/lib/libqueue.so:system//system/lib/libqueue.so \
    vendor/semc/iyokan/proprietary//system/lib/libuim.so:system//system/lib/libuim.so \
    vendor/semc/iyokan/proprietary//system/lib/libreference-ril.so:system//system/lib/libreference-ril.so \
    vendor/semc/iyokan/proprietary//system/lib/libril-qc-1.so:system//system/lib/libril-qc-1.so \
    vendor/semc/iyokan/proprietary//system/lib/libwms.so:system//system/lib/libwms.so \
    vendor/semc/iyokan/proprietary//system/lib/libwmsts.so:system//system/lib/libwmsts.so \
    vendor/semc/iyokan/proprietary//system/lib/libdsi_netctrl.so:system//system/lib/libdsi_netctrl.so \
    vendor/semc/iyokan/proprietary//system/lib/libdsutils.so:system//system/lib/libdsutils.so \
    vendor/semc/iyokan/proprietary//system/lib/libidl.so:system//system/lib/libidl.so \
    vendor/semc/iyokan/proprietary//system/lib/libnetmgr.so:system//system/lib/libnetmgr.so \
    vendor/semc/iyokan/proprietary//system/lib/libqdp.so:system//system/lib/libqdp.so \
    vendor/semc/iyokan/proprietary//system/bin/netmgrd:system//system/bin/netmgrd \
    vendor/semc/iyokan/proprietary//system/lib/libgsl.so/libgsl.so:system//system/lib/libgsl.so/libgsl.so \
    vendor/semc/iyokan/proprietary//system/lib/egl/libGLESv1_CM_adreno200.so:system//system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/semc/iyokan/proprietary//system/lib/egl/libq3dtools_adreno200.so:system//system/lib/egl/libq3dtools_adreno200.so \
    vendor/semc/iyokan/proprietary//system/lib/egl/libEGL_adreno200.so:system//system/lib/egl/libEGL_adreno200.so \
    vendor/semc/iyokan/proprietary//system/lib/egl/libGLESv2_adreno200.so:system//system/lib/egl/libGLESv2_adreno200.so \
    vendor/semc/iyokan/proprietary//system/lib/liboemcamera.so:system//system/lib/liboemcamera.so \
    vendor/semc/iyokan/proprietary//system/lib/libmmjpeg.so:system//system/lib/libmmjpeg.so \
    vendor/semc/iyokan/proprietary//system/lib/libmmipl.so:system//system/lib/libmmipl.so \
    vendor/semc/iyokan/proprietary//system/lib/libcamera.so:system//system/lib/libcamera.so \
    vendor/semc/iyokan/proprietary//system/lib/libcamera_clientsemc.so:system//system/lib/libcamera_clientsemc.so \
    vendor/semc/iyokan/proprietary//system/lib/libcald_client.so:system//system/lib/libcald_client.so \
    vendor/semc/iyokan/proprietary//system/lib/libcald_debugger.so:system//system/lib/libcald_debugger.so \
    vendor/semc/iyokan/proprietary//system/lib/libcald_hal.so:system//system/lib/libcald_hal.so \
    vendor/semc/iyokan/proprietary//system/lib/libcald_imageutil.so:system//system/lib/libcald_imageutil.so \
    vendor/semc/iyokan/proprietary//system/lib/libcald_pal.so:system//system/lib/libcald_pal.so \
    vendor/semc/iyokan/proprietary//system/lib/libcald_server.so:system//system/lib/libcald_server.so \
    vendor/semc/iyokan/proprietary//system/lib/libface.so:system//system/lib/libface.so \
    vendor/semc/iyokan/proprietary//system/lib/libgemini.so:system//system/lib/libgemini.so \
    vendor/semc/iyokan/proprietary//system/lib/libcameraextensionclient.so:system//system/lib/libcameraextensionclient.so \
    vendor/semc/iyokan/proprietary//system/lib/libcameraextensionjni.so:system//system/lib/libcameraextensionjni.so \
    vendor/semc/iyokan/proprietary//system/lib/libcameraextensionservice.so:system//system/lib/libcameraextensionservice.so \
    vendor/semc/iyokan/proprietary//system/lib/libcameralight.so:system//system/lib/libcameralight.so \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/LGI08BN1.dat:system//system/usr/semc/camera/LGI08BN1.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/SOD08BN1.dat:system//system/usr/semc/camera/SOD08BN1.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/SOD08BN0.dat:system//system/usr/semc/camera/SOD08BN0.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/SOD08BN0_IMX073.dat:system//system/usr/semc/camera/SOD08BN0_IMX073.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/LGI08BN0_IMX105.dat:system//system/usr/semc/camera/LGI08BN0_IMX105.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/LM3560_02_flash.dat:system//system/usr/semc/camera/LM3560_02_flash.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/LGI08BN0_DW9714.dat:system//system/usr/semc/camera/LGI08BN0_DW9714.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/SOD08BN1_DW9714.dat:system//system/usr/semc/camera/SOD08BN1_DW9714.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/APT00YP0_MT9V144.dat:system//system/usr/semc/camera/APT00YP0_MT9V144.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/APT00YP0.dat:system//system/usr/semc/camera/APT00YP0.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/SOD08BN1_IMX105.dat:system//system/usr/semc/camera/SOD08BN1_IMX105.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/SOD08BN0_DW9714.dat:system//system/usr/semc/camera/SOD08BN0_DW9714.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/LGI08BN1_DW9714.dat:system//system/usr/semc/camera/LGI08BN1_DW9714.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/LGI08BN0.dat:system//system/usr/semc/camera/LGI08BN0.dat \
    vendor/semc/iyokan/proprietary//system/usr/semc/camera/LGI08BN1_IMX105.dat:system//system/usr/semc/camera/LGI08BN1_IMX105.dat \
    vendor/semc/iyokan/proprietary//system/etc/firmware/bq27520_fw-0506_filever-0111_proj-hall_golden.bqfs:system//system/etc/firmware/bq27520_fw-0506_filever-0111_proj-hall_golden.bqfs \
    vendor/semc/iyokan/proprietary//system/etc/firmware/bq27520_fw-0506_filever-0111_proj-hall_golden.dffs:system//system/etc/firmware/bq27520_fw-0506_filever-0111_proj-hall_golden.dffs \
    vendor/semc/iyokan/proprietary//system/etc/firmware/fm_rx_init_1273.1.bts:system//system/etc/firmware/fm_rx_init_1273.1.bts \
    vendor/semc/iyokan/proprietary//system/etc/firmware/fm_rx_init_1273.2.bts:system//system/etc/firmware/fm_rx_init_1273.2.bts \
    vendor/semc/iyokan/proprietary//system/etc/firmware/fm_tx_init_1273.1.bts:system//system/etc/firmware/fm_tx_init_1273.1.bts \
    vendor/semc/iyokan/proprietary//system/etc/firmware/fm_tx_init_1273.2.bts:system//system/etc/firmware/fm_tx_init_1273.2.bts \
    vendor/semc/iyokan/proprietary//system/etc/firmware/fmc_init_1273.1.bts:system//system/etc/firmware/fmc_init_1273.1.bts \
    vendor/semc/iyokan/proprietary//system/etc/firmware/fmc_init_1273.2.bts:system//system/etc/firmware/fmc_init_1273.2.bts \
    vendor/semc/iyokan/proprietary//system/etc/firmware/TIInit_7.5.20.bts:system//system/etc/firmware/TIInit_7.5.20.bts \
    vendor/semc/iyokan/proprietary//system/etc/firmware/TIInit_7.6.15.bts:system//system/etc/firmware/TIInit_7.6.15.bts \
    vendor/semc/iyokan/proprietary//system/etc/firmware/vidc_720p_command_control.fw:system//system/etc/firmware/vidc_720p_command_control.fw \
    vendor/semc/iyokan/proprietary//system/etc/firmware/vidc_720p_h263_dec_mc.fw:system//system/etc/firmware/vidc_720p_h263_dec_mc.fw \
    vendor/semc/iyokan/proprietary//system/etc/firmware/vidc_720p_h264_dec_mc.fw:system//system/etc/firmware/vidc_720p_h264_dec_mc.fw \
    vendor/semc/iyokan/proprietary//system/etc/firmware/vidc_720p_h264_enc_mc.fw:system//system/etc/firmware/vidc_720p_h264_enc_mc.fw \
    vendor/semc/iyokan/proprietary//system/etc/firmware/vidc_720p_mp4_dec_mc.fw:system//system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
    vendor/semc/iyokan/proprietary//system/etc/firmware/vidc_720p_mp4_enc_mc.fw:system//system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
    vendor/semc/iyokan/proprietary//system/etc/firmware/vidc_720p_vc1_dec_mc.fw:system//system/etc/firmware/vidc_720p_vc1_dec_mc.fw \
    vendor/semc/iyokan/proprietary//system/etc/firmware/yamato_pfp.fw:system//system/etc/firmware/yamato_pfp.fw \
    vendor/semc/iyokan/proprietary//system/etc/firmware/yamato_pm4.fw:system//system/etc/firmware/yamato_pm4.fw \
    vendor/semc/iyokan/proprietary//system/bin/nvimport:system//system/bin/nvimport \
    vendor/semc/iyokan/proprietary//system/bin/hciattach:system//system/bin/hciattach \
    vendor/semc/iyokan/proprietary//system/etc/init.qcom.bt.sh:system//system/etc/init.qcom.bt.sh \
    vendor/semc/iyokan/proprietary//system/etc/tiwlan.ini:system//system/etc/tiwlan.ini \
    vendor/semc/iyokan/proprietary//system/etc/wifi/wpa_supplicant.conf:system//system/etc/wifi/wpa_supplicant.conf \
    vendor/semc/iyokan/proprietary//system/etc/wifi/softap/hostapd.conf:system//system/etc/wifi/softap/hostapd.conf \
    vendor/semc/iyokan/proprietary//system/etc/tiwlan_firmware.bin:system//system/etc/tiwlan_firmware.bin \
    vendor/semc/iyokan/proprietary//system/etc/wifi/softap/tiwlan_ap.ini:system//system/etc/wifi/softap/tiwlan_ap.ini \
    vendor/semc/iyokan/proprietary//system/etc/wifi/softap/softap_firmware.bin:system//system/etc/wifi/softap/softap_firmware.bin \
    vendor/semc/iyokan/proprietary//system/lib/libaudioalsa.so:system//system/lib/libaudioalsa.so \
    vendor/semc/iyokan/proprietary//system/lib/libaudioalsa.so:system//system/lib/libaudioalsa.so \
    vendor/semc/iyokan/proprietary//system/etc/vold.fstab:system//system/etc/vold.fstab \
    vendor/semc/iyokan/proprietary//system/etc/sensors.conf:system//system/etc/sensors.conf \
    vendor/semc/iyokan/proprietary//system/lib/hw/sensors.default.so:system//system/lib/hw/sensors.default.so \
    vendor/semc/iyokan/proprietary//system/bin/bq275xx_fwloader:system//system/bin/bq275xx_fwloader \
    vendor/semc/iyokan/proprietary//system/bin/akmd8975:system//system/bin/akmd8975 \
    vendor/semc/iyokan/proprietary//system/bin/chargemon:system//system/bin/chargemon \
    vendor/semc/iyokan/proprietary//system/lib/libmiscta.so:system//system/lib/libmiscta.so \
    vendor/semc/iyokan/proprietary//system/lib/hw/gps.msm7x30.so:system//system/lib/hw/gps.msm7x30.so \
    vendor/semc/iyokan/proprietary//system/etc/firmware/touch_iyokan_ttsp.hex:system//system/etc/firmware/touch_iyokan_ttsp.hex \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/keyprint.xml:system//system/usr/keyboard-config/keyprint.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/scancode_mapping.xml:system//system/usr/keyboard-config/scancode_mapping.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_ara.xml:system//system/usr/keyboard-config/languages/language_ara.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_bos.xml:system//system/usr/keyboard-config/languages/language_bos.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_bul.xml:system//system/usr/keyboard-config/languages/language_bul.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_cat.xml:system//system/usr/keyboard-config/languages/language_cat.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_ces.xml:system//system/usr/keyboard-config/languages/language_ces.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_dan.xml:system//system/usr/keyboard-config/languages/language_dan.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_deu.xml:system//system/usr/keyboard-config/languages/language_deu.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_ell.xml:system//system/usr/keyboard-config/languages/language_ell.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_eng.xml:system//system/usr/keyboard-config/languages/language_eng.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_esp.xml:system//system/usr/keyboard-config/languages/language_esp.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_est.xml:system//system/usr/keyboard-config/languages/language_est.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_eus.xml:system//system/usr/keyboard-config/languages/language_eus.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_fas.xml:system//system/usr/keyboard-config/languages/language_fas.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_fin.xml:system//system/usr/keyboard-config/languages/language_fin.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_fra.xml:system//system/usr/keyboard-config/languages/language_fra.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_glg.xml:system//system/usr/keyboard-config/languages/language_glg.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_heb.xml:system//system/usr/keyboard-config/languages/language_heb.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_hrv.xml:system//system/usr/keyboard-config/languages/language_hrv.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_hun.xml:system//system/usr/keyboard-config/languages/language_hun.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_ind.xml:system//system/usr/keyboard-config/languages/language_ind.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_isl.xml:system//system/usr/keyboard-config/languages/language_isl.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_ita.xml:system//system/usr/keyboard-config/languages/language_ita.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_jav.xml:system//system/usr/keyboard-config/languages/language_jav.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_kaz.xml:system//system/usr/keyboard-config/languages/language_kaz.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_lav.xml:system//system/usr/keyboard-config/languages/language_lav.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_lit.xml:system//system/usr/keyboard-config/languages/language_lit.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_mkd.xml:system//system/usr/keyboard-config/languages/language_mkd.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_msa.xml:system//system/usr/keyboard-config/languages/language_msa.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_nld.xml:system//system/usr/keyboard-config/languages/language_nld.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_nor.xml:system//system/usr/keyboard-config/languages/language_nor.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_pol.xml:system//system/usr/keyboard-config/languages/language_pol.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_por.xml:system//system/usr/keyboard-config/languages/language_por.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_ron.xml:system//system/usr/keyboard-config/languages/language_ron.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_rus.xml:system//system/usr/keyboard-config/languages/language_rus.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_slk.xml:system//system/usr/keyboard-config/languages/language_slk.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_slv.xml:system//system/usr/keyboard-config/languages/language_slv.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_sqi.xml:system//system/usr/keyboard-config/languages/language_sqi.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_srp.xml:system//system/usr/keyboard-config/languages/language_srp.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_sun.xml:system//system/usr/keyboard-config/languages/language_sun.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_swe.xml:system//system/usr/keyboard-config/languages/language_swe.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_tgl.xml:system//system/usr/keyboard-config/languages/language_tgl.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_tha.xml:system//system/usr/keyboard-config/languages/language_tha.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_tur.xml:system//system/usr/keyboard-config/languages/language_tur.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_ukr.xml:system//system/usr/keyboard-config/languages/language_ukr.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/languages/language_vie.xml:system//system/usr/keyboard-config/languages/language_vie.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/arabic.xml:system//system/usr/keyboard-config/layouts/arabic.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/azerty.xml:system//system/usr/keyboard-config/layouts/azerty.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/bopomofo.xml:system//system/usr/keyboard-config/layouts/bopomofo.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/cyrillic.xml:system//system/usr/keyboard-config/layouts/cyrillic.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/greek.xml:system//system/usr/keyboard-config/layouts/greek.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/hebrew.xml:system//system/usr/keyboard-config/layouts/hebrew.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/korean.xml:system//system/usr/keyboard-config/layouts/korean.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/qwerty-br.xml:system//system/usr/keyboard-config/layouts/qwerty-br.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/qwerty-cn-hk.xml:system//system/usr/keyboard-config/layouts/qwerty-cn-hk.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/qwerty-en.xml:system//system/usr/keyboard-config/layouts/qwerty-en.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/qwerty-jp.xml:system//system/usr/keyboard-config/layouts/qwerty-jp.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/qwerty-no-dk.xml:system//system/usr/keyboard-config/layouts/qwerty-no-dk.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/qwerty-se-fi.xml:system//system/usr/keyboard-config/layouts/qwerty-se-fi.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/qwertz.xml:system//system/usr/keyboard-config/layouts/qwertz.xml \
    vendor/semc/iyokan/proprietary//system/usr/keyboard-config/layouts/thai.xml:system//system/usr/keyboard-config/layouts/thai.xml \
    vendor/semc/iyokan/proprietary//system/bin/hdmid:system//system/bin/hdmid \
    vendor/semc/iyokan/proprietary//system/lib/libhdmidisplay.so:system//system/lib/libhdmidisplay.so \
    vendor/semc/iyokan/proprietary//system/app/SemcHdmiControlService.apk:system//system/app/SemcHdmiControlService.apk \
    vendor/semc/iyokan/proprietary//system/framework/com.sonyericsson.privateapis_impl.jar:system//system/framework/com.sonyericsson.privateapis_impl.jar \
    vendor/semc/iyokan/proprietary//system/etc/permissions/com.sonyericsson.privateapis.xml:system//system/etc/permissions/com.sonyericsson.privateapis.xml \
    vendor/semc/iyokan/proprietary//system/app/AntHalService.apk:system//system/app/AntHalService.apk \
    vendor/semc/iyokan/proprietary//system/etc/permissions/com.dsi.ant.antradio_library.xml:system//system/etc/permissions/com.dsi.ant.antradio_library.xml \
    vendor/semc/iyokan/proprietary//system/framework/com.dsi.ant.antradio_library.jar:system//system/framework/com.dsi.ant.antradio_library.jar \
    vendor/semc/iyokan/proprietary//system/lib/libanthal.so:system//system/lib/libanthal.so
