
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/iyokan/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries

# Prebuilt kl keymaps
PRODUCT_COPY_FILES += \
vendor/semc/iyokan/proprietary/qwerty.kcm.bin:system/usr/keychars/qwerty.kcm.bin \
vendor/semc/iyokan/proprietary/qwerty.kcm.bin:system/usr/keychars/pm8058-keypad.kcm.bin \
vendor/semc/iyokan/proprietary/qwerty2.kcm.bin:system/usr/keychars/qwerty2.kcm.bin \
vendor/semc/iyokan/proprietary/atdaemon.kl:system/usr/keylayout/atdaemon.kl \
vendor/semc/iyokan/proprietary/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
vendor/semc/iyokan/proprietary/msm_pmic_pwr_key.kl:system/usr/keylayout/msm_pmic_pwr_key.kl \
vendor/semc/iyokan/proprietary/pm8058-keypad.kl:system/usr/keylayout/pm8058-keypad.kl \
vendor/semc/iyokan/proprietary/qwerty.kl:system/usr/keylayout/qwerty.kl \
vendor/semc/iyokan/proprietary/simple_remote.kl:system/usr/keylayout/simple_remote.kl

## RIL related stuff 
PRODUCT_COPY_FILES += \
vendor/semc/iyokan/proprietary/libril.so:system/lib/libril.so \
vendor/semc/iyokan/proprietary/port-bridge:system/bin/port-bridge \
vendor/semc/iyokan/proprietary/qmuxd:system/bin/qmuxd \
vendor/semc/iyokan/proprietary/libauth.so:system/lib/libauth.so \
vendor/semc/iyokan/proprietary/libcm.so:system/lib/libcm.so \
vendor/semc/iyokan/proprietary/libdiag.so:system/lib/libdiag.so \
vendor/semc/iyokan/proprietary/libdll.so:system/lib/libdll.so \
vendor/semc/iyokan/proprietary/libdsm.so:system/lib/libdsm.so \
vendor/semc/iyokan/proprietary/libdss.so:system/lib/libdss.so \
vendor/semc/iyokan/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
vendor/semc/iyokan/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
vendor/semc/iyokan/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
vendor/semc/iyokan/proprietary/libnv.so:system/lib/libnv.so \
vendor/semc/iyokan/proprietary/liboem_rapi.so:system/lib/liboem_rapi.so \
vendor/semc/iyokan/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
vendor/semc/iyokan/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
vendor/semc/iyokan/proprietary/libqmi.so:system/lib/libqmi.so \
vendor/semc/iyokan/proprietary/libqueue.so:system/lib/libqueue.so \
vendor/semc/iyokan/proprietary/libuim.so:system/lib/libuim.so \
vendor/semc/iyokan/proprietary/libreference-ril.so:system/lib/libreference-ril.so \
vendor/semc/iyokan/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
vendor/semc/iyokan/proprietary/libwms.so:system/lib/libwms.so \
vendor/semc/iyokan/proprietary/libwmsts.so:system/lib/libwmsts.so \
vendor/semc/iyokan/proprietary/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
vendor/semc/iyokan/proprietary/libdsutils.so:system/lib/libdsutils.so \
vendor/semc/iyokan/proprietary/libidl.so:system/lib/libidl.so \
vendor/semc/iyokan/proprietary/libnetmgr.so:system/lib/libnetmgr.so \
vendor/semc/iyokan/proprietary/libqdp.so:system/lib/libqdp.so \
vendor/semc/iyokan/proprietary/netmgrd:system/bin/netmgrd

## Camera proprietaries
PRODUCT_COPY_FILES += \
vendor/semc/iyokan/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
vendor/semc/iyokan/proprietary/libcamera.so:obj/lib/libcamera.so \
vendor/semc/iyokan/proprietary/libcamera.so:system/lib/libcamera.so \
vendor/semc/iyokan/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
vendor/semc/iyokan/proprietary/libmmipl.so:system/lib/libmmipl.so \
vendor/semc/iyokan/proprietary/libcald_client.so:system/lib/libcald_client.so \
vendor/semc/iyokan/proprietary/libcald_debugger.so:system/lib/libcald_debugger.so \
vendor/semc/iyokan/proprietary/libcald_hal.so:system/lib/libcald_hal.so \
vendor/semc/iyokan/proprietary/libcald_imageutil.so:system/lib/libcald_imageutil.so \
vendor/semc/iyokan/proprietary/libcald_pal.so:system/lib/libcald_pal.so \
vendor/semc/iyokan/proprietary/libcald_server.so:system/lib/libcald_server.so \
vendor/semc/iyokan/proprietary/libcameraextensionclient.so:system/lib/libcameraextensionclient.so \
vendor/semc/iyokan/proprietary/libcameraextensionjni.so:system/lib/libcameraextensionjni.so \
vendor/semc/iyokan/proprietary/libcameraextensionservice.so:system/lib/libcameraextensionservice.so \
vendor/semc/iyokan/proprietary/libface.so:system/lib/libface.so \
vendor/semc/iyokan/proprietary/libgemini.so:system/lib/libgemini.so \
vendor/semc/iyokan/proprietary/libcameralight.so:system/lib/libcameralight.so \
vendor/semc/iyokan/proprietary/LGI08BN1.dat:system/usr/semc/camera/LGI08BN1.dat \
vendor/semc/iyokan/proprietary/SOD08BN1.dat:system/usr/semc/camera/SOD08BN1.dat \
vendor/semc/iyokan/proprietary/SOD08BN0.dat:system/usr/semc/camera/SOD08BN0.dat \
vendor/semc/iyokan/proprietary/SOD08BN0_IMX073.dat:system/usr/semc/camera/SOD08BN0_IMX073.dat \
vendor/semc/iyokan/proprietary/LGI08BN0_IMX105.dat:system/usr/semc/camera/LGI08BN0_IMX105.dat \
vendor/semc/iyokan/proprietary/LM3560_02_flash.dat:system/usr/semc/camera/LM3560_02_flash.dat \
vendor/semc/iyokan/proprietary/LGI08BN0_DW9714.dat:system/usr/semc/camera/LGI08BN0_DW9714.dat \
vendor/semc/iyokan/proprietary/SOD08BN1_DW9714.dat:system/usr/semc/camera/SOD08BN1_DW9714.dat \
vendor/semc/iyokan/proprietary/APT00YP0_MT9V144.dat:system/usr/semc/camera/APT00YP0_MT9V144.dat \
vendor/semc/iyokan/proprietary/APT00YP0.dat:system/usr/semc/camera/APT00YP0.dat \
vendor/semc/iyokan/proprietary/SOD08BN1_IMX105.dat:system/usr/semc/camera/SOD08BN1_IMX105.dat \
vendor/semc/iyokan/proprietary/SOD08BN0_DW9714.dat:system/usr/semc/camera/SOD08BN0_DW9714.dat \
vendor/semc/iyokan/proprietary/LGI08BN1_DW9714.dat:system/usr/semc/camera/LGI08BN1_DW9714.dat \
vendor/semc/iyokan/proprietary/LGI08BN0.dat:system/usr/semc/camera/LGI08BN0.dat \
vendor/semc/iyokan/proprietary/LGI08BN1_IMX105.dat:system/usr/semc/camera/LGI08BN1_IMX105.dat \

## FIRMWARE
PRODUCT_COPY_FILES += \
vendor/semc/iyokan/proprietary/bq27520_fw-0506_filever-0111_proj-hall_golden.bqfs:system/etc/firmware/bq27520_fw-0506_filever-0111_proj-hall_golden.bqfs \
vendor/semc/iyokan/proprietary/bq27520_fw-0506_filever-0111_proj-hall_golden.dffs:system/etc/firmware/bq27520_fw-0506_filever-0111_proj-hall_golden.dffs \
vendor/semc/iyokan/proprietary/fm_rx_init_1273.1.bts:system/etc/firmware/fm_rx_init_1273.1.bts \
vendor/semc/iyokan/proprietary/fm_rx_init_1273.2.bts:system/etc/firmware/fm_rx_init_1273.2.bts \
vendor/semc/iyokan/proprietary/fm_tx_init_1273.1.bts:system/etc/firmware/fm_tx_init_1273.1.bts \
vendor/semc/iyokan/proprietary/fm_tx_init_1273.2.bts:system/etc/firmware/fm_tx_init_1273.2.bts \
vendor/semc/iyokan/proprietary/fmc_init_1273.1.bts:system/etc/firmware/fmc_init_1273.1.bts \
vendor/semc/iyokan/proprietary/fmc_init_1273.2.bts:system/etc/firmware/fmc_init_1273.2.bts \
vendor/semc/iyokan/proprietary/TIInit_7.5.20.bts:system/etc/firmware/TIInit_7.5.20.bts \
vendor/semc/iyokan/proprietary/TIInit_7.6.15.bts:system/etc/firmware/TIInit_7.6.15.bts \
vendor/semc/iyokan/proprietary/vidc_720p_command_control.fw:system/etc/firmware/vidc_720p_command_control.fw \
vendor/semc/iyokan/proprietary/vidc_720p_h263_dec_mc.fw:system/etc/firmware/vidc_720p_h263_dec_mc.fw \
vendor/semc/iyokan/proprietary/vidc_720p_h264_dec_mc.fw:system/etc/firmware/vidc_720p_h264_dec_mc.fw \
vendor/semc/iyokan/proprietary/vidc_720p_h264_enc_mc.fw:system/etc/firmware/vidc_720p_h264_enc_mc.fw \
vendor/semc/iyokan/proprietary/vidc_720p_mp4_dec_mc.fw:system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
vendor/semc/iyokan/proprietary/vidc_720p_mp4_enc_mc.fw:system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
vendor/semc/iyokan/proprietary/vidc_720p_vc1_dec_mc.fw:system/etc/firmware/vidc_720p_vc1_dec_mc.fw \
vendor/semc/iyokan/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
vendor/semc/iyokan/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw 

## WIFI & BT TI1271
PRODUCT_COPY_FILES += \
vendor/semc/iyokan/proprietary/hciattach:system/bin/hciattach \
vendor/semc/iyokan/proprietary/init.qcom.bt.sh:system/etc/init.bt.sh \
vendor/semc/iyokan/proprietary/tiwlan.ini:system/etc/wifi/tiwlan.ini \
vendor/semc/iyokan/proprietary/tiwlan_firmware.bin:system/etc/wifi/tiwlan_firmware.bin \
vendor/semc/iyokan/proprietary/tiwlan_ap.ini:system/etc/wifi/softap/tiwlan_ap.ini \
vendor/semc/iyokan/proprietary/softap_firmware.bin:system/etc/wifi/softap/tiwlan_firmware_ap.bin \
vendor/semc/iyokan/proprietary/nvimport:system/bin/nvimport

## Other libraries and proprietary binaries
PRODUCT_COPY_FILES += \
vendor/semc/iyokan/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
vendor/semc/iyokan/proprietary/libaudioalsa.so:system/lib/libaudioalsa.so \
vendor/semc/iyokan/proprietary/vold.fstab:system/etc/vold.fstab \
vendor/semc/iyokan/proprietary/sensors.conf:system/etc/sensors.conf \
vendor/semc/iyokan/proprietary/sensors.default.so:system/lib/hw/sensors.semc.so \
vendor/semc/iyokan/proprietary/bq275xx_fwloader:system/bin/bq275xx_fwloader \
vendor/semc/iyokan/proprietary/akmd8975:system/bin/akmd8975 \

#offline charging animation
PRODUCT_COPY_FILES += \
vendor/semc/iyokan/proprietary/chargemon:system/bin/chargemon \
vendor/semc/iyokan/proprietary/libmiscta.so:system/lib/libmiscta.so

#Temporary GPS Fix untill we have 50001 gps
PRODUCT_COPY_FILES += \
vendor/semc/iyokan/proprietary/gps.msm7x30.so:system/lib/hw/gps.semc.so

#touch
PRODUCT_COPY_FILES += \
vendor/semc/iyokan/proprietary/touch_iyokan_ttsp.hex:system/etc/firmware/touch_iyokan_ttsp.hex

## Adreno 200 files
PRODUCT_COPY_FILES += \
vendor/semc/iyokan/proprietary/libgsl.so:system/lib/libgsl.so \
vendor/semc/iyokan/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
vendor/semc/iyokan/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
vendor/semc/iyokan/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
vendor/semc/iyokan/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so

#hardware keyboard layout
PRODUCT_COPY_FILES += \
vendor/semc/iyokan/proprietary/keyprint.xml:system/usr/keyboard-config/keyprint.xml \
vendor/semc/iyokan/proprietary/scancode_mapping.xml:system/usr/keyboard-config//scancode_mapping.xml \
vendor/semc/iyokan/proprietary/language_ara.xml:system/usr/keyboard-config/languages/language_ara.xml \
vendor/semc/iyokan/proprietary/language_bos.xml:system/usr/keyboard-config/languages/language_bos.xml \
vendor/semc/iyokan/proprietary/language_bul.xml:system/usr/keyboard-config/languages/language_bul.xml \
vendor/semc/iyokan/proprietary/language_cat.xml:system/usr/keyboard-config/languages/language_cat.xml \
vendor/semc/iyokan/proprietary/language_ces.xml:system/usr/keyboard-config/languages/language_ces.xml \
vendor/semc/iyokan/proprietary/language_dan.xml:system/usr/keyboard-config/languages/language_dan.xml \
vendor/semc/iyokan/proprietary/language_deu.xml:system/usr/keyboard-config/languages/language_deu.xml \
vendor/semc/iyokan/proprietary/language_ell.xml:system/usr/keyboard-config/languages/language_ell.xml \
vendor/semc/iyokan/proprietary/language_eng.xml:system/usr/keyboard-config/languages/language_eng.xml \
vendor/semc/iyokan/proprietary/language_esp.xml:system/usr/keyboard-config/languages/language_esp.xml \
vendor/semc/iyokan/proprietary/language_est.xml:system/usr/keyboard-config/languages/language_est.xml \
vendor/semc/iyokan/proprietary/language_eus.xml:system/usr/keyboard-config/languages/language_eus.xml \
vendor/semc/iyokan/proprietary/language_fas.xml:system/usr/keyboard-config/languages/language_fas.xml \
vendor/semc/iyokan/proprietary/language_fin.xml:system/usr/keyboard-config/languages/language_fin.xml \
vendor/semc/iyokan/proprietary/language_fra.xml:system/usr/keyboard-config/languages/language_fra.xml \
vendor/semc/iyokan/proprietary/language_glg.xml:system/usr/keyboard-config/languages/language_glg.xml \
vendor/semc/iyokan/proprietary/language_heb.xml:system/usr/keyboard-config/languages/language_heb.xml \
vendor/semc/iyokan/proprietary/language_hrv.xml:system/usr/keyboard-config/languages/language_hrv.xml \
vendor/semc/iyokan/proprietary/language_hun.xml:system/usr/keyboard-config/languages/language_hun.xml \
vendor/semc/iyokan/proprietary/language_ind.xml:system/usr/keyboard-config/languages/language_ind.xml \
vendor/semc/iyokan/proprietary/language_isl.xml:system/usr/keyboard-config/languages/language_isl.xml \
vendor/semc/iyokan/proprietary/language_ita.xml:system/usr/keyboard-config/languages/language_ita.xml \
vendor/semc/iyokan/proprietary/language_jav.xml:system/usr/keyboard-config/languages/language_jav.xml \
vendor/semc/iyokan/proprietary/language_kaz.xml:system/usr/keyboard-config/languages/language_kaz.xml \
vendor/semc/iyokan/proprietary/language_lav.xml:system/usr/keyboard-config/languages/language_lav.xml \
vendor/semc/iyokan/proprietary/language_lit.xml:system/usr/keyboard-config/languages/language_lit.xml \
vendor/semc/iyokan/proprietary/language_mkd.xml:system/usr/keyboard-config/languages/language_mkd.xml \
vendor/semc/iyokan/proprietary/language_msa.xml:system/usr/keyboard-config/languages/language_msa.xml \
vendor/semc/iyokan/proprietary/language_nld.xml:system/usr/keyboard-config/languages/language_nld.xml \
vendor/semc/iyokan/proprietary/language_nor.xml:system/usr/keyboard-config/languages/language_nor.xml \
vendor/semc/iyokan/proprietary/language_pol.xml:system/usr/keyboard-config/languages/language_pol.xml \
vendor/semc/iyokan/proprietary/language_por.xml:system/usr/keyboard-config/languages/language_por.xml \
vendor/semc/iyokan/proprietary/language_ron.xml:system/usr/keyboard-config/languages/language_ron.xml \
vendor/semc/iyokan/proprietary/language_rus.xml:system/usr/keyboard-config/languages/language_rus.xml \
vendor/semc/iyokan/proprietary/language_slk.xml:system/usr/keyboard-config/languages/language_slk.xml \
vendor/semc/iyokan/proprietary/language_slv.xml:system/usr/keyboard-config/languages/language_slv.xml \
vendor/semc/iyokan/proprietary/language_sqi.xml:system/usr/keyboard-config/languages/language_sqi.xml \
vendor/semc/iyokan/proprietary/language_srp.xml:system/usr/keyboard-config/languages/language_srp.xml \
vendor/semc/iyokan/proprietary/language_sun.xml:system/usr/keyboard-config/languages/language_sun.xml \
vendor/semc/iyokan/proprietary/language_swe.xml:system/usr/keyboard-config/languages/language_swe.xml \
vendor/semc/iyokan/proprietary/language_tgl.xml:system/usr/keyboard-config/languages/language_tgl.xml \
vendor/semc/iyokan/proprietary/language_tha.xml:system/usr/keyboard-config/languages/language_tha.xml \
vendor/semc/iyokan/proprietary/language_tur.xml:system/usr/keyboard-config/languages/language_tur.xml \
vendor/semc/iyokan/proprietary/language_ukr.xml:system/usr/keyboard-config/languages/language_ukr.xml \
vendor/semc/iyokan/proprietary/language_vie.xml:system/usr/keyboard-config/languages/language_vie.xml \
vendor/semc/iyokan/proprietary/arabic.xml:system/usr/keyboard-config/layouts/arabic.xml \
vendor/semc/iyokan/proprietary/azerty.xml:system/usr/keyboard-config/layouts/azerty.xml \
vendor/semc/iyokan/proprietary/bopomofo.xml:system/usr/keyboard-config/layouts/bopomofo.xml \
vendor/semc/iyokan/proprietary/cyrillic.xml:system/usr/keyboard-config/layouts/cyrillic.xml \
vendor/semc/iyokan/proprietary/greek.xml:system/usr/keyboard-config/layouts/greek.xml \
vendor/semc/iyokan/proprietary/hebrew.xml:system/usr/keyboard-config/layouts/hebrew.xml \
vendor/semc/iyokan/proprietary/korean.xml:system/usr/keyboard-config/layouts/korean.xml \
vendor/semc/iyokan/proprietary/qwerty-br.xml:system/usr/keyboard-config/layouts/qwerty-br.xml \
vendor/semc/iyokan/proprietary/qwerty-cn-hk.xml:system/usr/keyboard-config/layouts/qwerty-cn-hk.xml \
vendor/semc/iyokan/proprietary/qwerty-en.xml:system/usr/keyboard-config/layouts/qwerty-en.xml \
vendor/semc/iyokan/proprietary/qwerty-jp.xml:system/usr/keyboard-config/layouts/qwerty-jp.xml \
vendor/semc/iyokan/proprietary/qwerty-no-dk.xml:system/usr/keyboard-config/layouts/qwerty-no-dk.xml \
vendor/semc/iyokan/proprietary/qwerty-se-fi.xml:system/usr/keyboard-config/layouts/qwerty-se-fi.xml \
vendor/semc/iyokan/proprietary/qwertz.xml:system/usr/keyboard-config/layouts/qwertz.xml \
vendor/semc/iyokan/proprietary/thai.xml:system/usr/keyboard-config/layouts/thai.xml 


