# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/shakira/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/semc/shakira/proprietary/lib/libcamera.so:obj/lib/libcamera.so

PRODUCT_COPY_FILES += \
    vendor/semc/shakira/proprietary//system/usr/keylayout/shakira_keypad.kl:system//system/usr/keylayout/shakira_keypad.kl \
    vendor/semc/shakira/proprietary//system/usr/keylayout/systemconnector.kl:system//system/usr/keylayout/systemconnector.kl \
    vendor/semc/shakira/proprietary//system/usr/keychars/shakira_keypad.kcm.bin:system//system/usr/keychars/shakira_keypad.kcm.bin \
    vendor/semc/shakira/proprietary//system/usr/keychars/systemconnector.kcm.bin:system//system/usr/keychars/systemconnector.kcm.bin \
    vendor/semc/shakira/proprietary//system/lib/libril.so:system//system/lib/libril.so \
    vendor/semc/shakira/proprietary//system/bin/port-bridge:system//system/bin/port-bridge \
    vendor/semc/shakira/proprietary//system/bin/qmuxd:system//system/bin/qmuxd \
    vendor/semc/shakira/proprietary//system/lib/libauth.so:system//system/lib/libauth.so \
    vendor/semc/shakira/proprietary//system/lib/libcm.so:system//system/lib/libcm.so \
    vendor/semc/shakira/proprietary//system/lib/libdiag.so:system//system/lib/libdiag.so \
    vendor/semc/shakira/proprietary//system/lib/libdll.so:system//system/lib/libdll.so \
    vendor/semc/shakira/proprietary//system/lib/libdsm.so:system//system/lib/libdsm.so \
    vendor/semc/shakira/proprietary//system/lib/libdss.so:system//system/lib/libdss.so \
    vendor/semc/shakira/proprietary//system/lib/libgsdi_exp.so:system//system/lib/libgsdi_exp.so \
    vendor/semc/shakira/proprietary//system/lib/libgstk_exp.so:system//system/lib/libgstk_exp.so \
    vendor/semc/shakira/proprietary//system/lib/libmmgsdilib.so:system//system/lib/libmmgsdilib.so \
    vendor/semc/shakira/proprietary//system/lib/libnv.so:system//system/lib/libnv.so \
    vendor/semc/shakira/proprietary//system/lib/liboem_rapi.so:system//system/lib/liboem_rapi.so \
    vendor/semc/shakira/proprietary//system/lib/liboncrpc.so:system//system/lib/liboncrpc.so \
    vendor/semc/shakira/proprietary//system/lib/libpbmlib.so:system//system/lib/libpbmlib.so \
    vendor/semc/shakira/proprietary//system/lib/libqmi.so:system//system/lib/libqmi.so \
    vendor/semc/shakira/proprietary//system/lib/libqueue.so:system//system/lib/libqueue.so \
    vendor/semc/shakira/proprietary//system/lib/libuim.so:system//system/lib/libuim.so \
    vendor/semc/shakira/proprietary//system/lib/libril-qc-1.so:system//system/lib/libril-qc-1.so \
    vendor/semc/shakira/proprietary//system/lib/libwms.so:system//system/lib/libwms.so \
    vendor/semc/shakira/proprietary//system/lib/libwmsts.so:system//system/lib/libwmsts.so \
    vendor/semc/shakira/proprietary//system/lib/liboemcamera.so:system//system/lib/liboemcamera.so \
    vendor/semc/shakira/proprietary//system/lib/libmmjpeg.so:system//system/lib/libmmjpeg.so \
    vendor/semc/shakira/proprietary//system/lib/libmmipl.so:system//system/lib/libmmipl.so \
    vendor/semc/shakira/proprietary//system/lib/libcamera.so:system//system/lib/libcamera.so \
    vendor/semc/shakira/proprietary//system/lib/libopencore_common.so:system//system/lib/libopencore_common.so \
    vendor/semc/shakira/proprietary//system/lib/libmm-adspsvc.so:system//system/lib/libmm-adspsvc.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxAacDec.so:system//system/lib/libOmxAacDec.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxAmrRtpDec.so:system//system/lib/libOmxAmrRtpDec.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxH264Dec.so:system//system/lib/libOmxH264Dec.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxQcelpDec.so:system//system/lib/libOmxQcelpDec.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxAacEnc.so:system//system/lib/libOmxAacEnc.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxAmrwbDec.so:system//system/lib/libOmxAmrwbDec.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxMp3Dec.so:system//system/lib/libOmxMp3Dec.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxVidEnc.so:system//system/lib/libOmxVidEnc.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxAmrDec.so:system//system/lib/libOmxAmrDec.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxEvrcDec.so:system//system/lib/libOmxEvrcDec.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxMpeg4Dec.so:system//system/lib/libOmxMpeg4Dec.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxWmaDec.so:system//system/lib/libOmxWmaDec.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxAmrEnc.so:system//system/lib/libOmxAmrEnc.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxEvrcEnc.so:system//system/lib/libOmxEvrcEnc.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxQcelp13Enc.so:system//system/lib/libOmxQcelp13Enc.so \
    vendor/semc/shakira/proprietary//system/lib/libOmxWmvDec.so:system//system/lib/libOmxWmvDec.so \
    vendor/semc/shakira/proprietary//system/etc/firmware/yamato_pfp.fw:system//system/etc/firmware/yamato_pfp.fw \
    vendor/semc/shakira/proprietary//system/etc/firmware/yamato_pm4.fw:system//system/etc/firmware/yamato_pm4.fw \
    vendor/semc/shakira/proprietary//system/etc/firmware/fm_rx_init_1273.1.bts:system//system/etc/firmware/fm_rx_init_1273.1.bts \
    vendor/semc/shakira/proprietary//system/etc/firmware/fm_rx_init_1273.2.bts:system//system/etc/firmware/fm_rx_init_1273.2.bts \
    vendor/semc/shakira/proprietary//system/etc/firmware/fm_tx_init_1273.1.bts:system//system/etc/firmware/fm_tx_init_1273.1.bts \
    vendor/semc/shakira/proprietary//system/etc/firmware/fm_tx_init_1273.2.bts:system//system/etc/firmware/fm_tx_init_1273.2.bts \
    vendor/semc/shakira/proprietary//system/etc/firmware/fmc_init_1273.1.bts:system//system/etc/firmware/fmc_init_1273.1.bts \
    vendor/semc/shakira/proprietary//system/etc/firmware/fmc_init_1273.2.bts:system//system/etc/firmware/fmc_init_1273.2.bts \
    vendor/semc/shakira/proprietary//system/etc/firmware/TIInit_7.2.31.bts:system//system/etc/firmware/TIInit_7.2.31.bts \
    vendor/semc/shakira/proprietary//system/bin/nvimport:system//system/bin/nvimport \
    vendor/semc/shakira/proprietary//system/bin/hciattach:system//system/bin/hciattach \
    vendor/semc/shakira/proprietary//system/etc/tiwlan.ini:system//system/etc/tiwlan.ini \
    vendor/semc/shakira/proprietary//system/etc/wifi/wpa_supplicant.conf:system//system/etc/wifi/wpa_supplicant.conf \
    vendor/semc/shakira/proprietary//system/etc/tiwlan_firmware.bin:system//system/etc/tiwlan_firmware.bin \
    vendor/semc/shakira/proprietary//system/lib/libgsl.so/libgsl.so:system//system/lib/libgsl.so/libgsl.so \
    vendor/semc/shakira/proprietary//system/lib/egl/libGLESv1_CM_adreno200.so:system//system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/semc/shakira/proprietary//system/lib/egl/libq3dtools_adreno200.so:system//system/lib/egl/libq3dtools_adreno200.so \
    vendor/semc/shakira/proprietary//system/lib/egl/libEGL_adreno200.so:system//system/lib/egl/libEGL_adreno200.so \
    vendor/semc/shakira/proprietary//system/lib/egl/libGLESv2_adreno200.so:system//system/lib/egl/libGLESv2_adreno200.so \
    vendor/semc/shakira/proprietary//system/lib/libaudioeq.so:system//system/lib/libaudioeq.so \
    vendor/semc/shakira/proprietary//system/etc/sensors.conf:system//system/etc/sensors.conf \
    vendor/semc/shakira/proprietary//system/bin/akmd2:system//system/bin/akmd2 \
    vendor/semc/shakira/proprietary//system/bin/chargemon:system//system/bin/chargemon \
    vendor/semc/shakira/proprietary//system/bin/semc_chargalg:system//system/bin/semc_chargalg \
    vendor/semc/shakira/proprietary//system/bin/updatemiscta:system//system/bin/updatemiscta \
    vendor/semc/shakira/proprietary//system/lib/libmiscta.so:system//system/lib/libmiscta.so \
    vendor/semc/shakira/proprietary//system/lib/hw/copybit.msm7k.so:system//system/lib/hw/copybit.msm7k.so \
    vendor/semc/shakira/proprietary//system/lib/hw/sensors.default.so:system//system/lib/hw/sensors.default.so \
    vendor/semc/shakira/proprietary//system/lib/hw/hal_seport.default.so:system//system/lib/hw/hal_seport.default.so \
    vendor/semc/shakira/proprietary//system/lib/libsystemconnector/libuinputdevicejni.so:system//system/lib/libsystemconnector/libuinputdevicejni.so \
    vendor/semc/shakira/proprietary//system/lib/libsystemconnector_hal_jni.so:system//system/lib/libsystemconnector_hal_jni.so \
    vendor/semc/shakira/proprietary//system/app/AntHalService.apk:system//system/app/AntHalService.apk \
    vendor/semc/shakira/proprietary//system/etc/permissions/com.dsi.ant.antradio_library.xml:system//system/etc/permissions/com.dsi.ant.antradio_library.xml \
    vendor/semc/shakira/proprietary//system/framework/com.dsi.ant.antradio_library.jar:system//system/framework/com.dsi.ant.antradio_library.jar \
    vendor/semc/shakira/proprietary//system/lib/libanthal.so:system//system/lib/libanthal.so
