
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/shakira/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries

# Prebuilt kl keymaps
PRODUCT_COPY_FILES += \
vendor/semc/shakira/proprietary/shakira_keypad.kl:system/usr/keylayout/shakira_keypad.kl \
vendor/semc/shakira/proprietary/systemconnector.kl:system/usr/keylayout/systemconnector.kl \
vendor/semc/shakira/proprietary/shakira_keypad.kcm.bin:system/usr/keychars/shakira_keypad.kcm.bin \
vendor/semc/shakira/proprietary/systemconnector.kcm.bin:system/usr/keychars/systemconnector.kcm.bin

## RIL related stuff 
PRODUCT_COPY_FILES += \
vendor/semc/shakira/proprietary/libril.so:system/lib/libril.so \
vendor/semc/shakira/proprietary/port-bridge:system/bin/port-bridge \
vendor/semc/shakira/proprietary/qmuxd:system/bin/qmuxd \
vendor/semc/shakira/proprietary/libauth.so:system/lib/libauth.so \
vendor/semc/shakira/proprietary/libcm.so:system/lib/libcm.so \
vendor/semc/shakira/proprietary/libdiag.so:system/lib/libdiag.so \
vendor/semc/shakira/proprietary/libdll.so:system/lib/libdll.so \
vendor/semc/shakira/proprietary/libdsm.so:system/lib/libdsm.so \
vendor/semc/shakira/proprietary/libdss.so:system/lib/libdss.so \
vendor/semc/shakira/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
vendor/semc/shakira/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
vendor/semc/shakira/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
vendor/semc/shakira/proprietary/libnv.so:system/lib/libnv.so \
vendor/semc/shakira/proprietary/liboem_rapi.so:system/lib/liboem_rapi.so \
vendor/semc/shakira/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
vendor/semc/shakira/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
vendor/semc/shakira/proprietary/libqmi.so:system/lib/libqmi.so \
vendor/semc/shakira/proprietary/libqueue.so:system/lib/libqueue.so \
vendor/semc/shakira/proprietary/libuim.so:system/lib/libuim.so \
vendor/semc/shakira/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
vendor/semc/shakira/proprietary/libwms.so:system/lib/libwms.so \
vendor/semc/shakira/proprietary/libwmsts.so:system/lib/libwmsts.so

## Camera proprietaries
PRODUCT_COPY_FILES += \
vendor/semc/shakira/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
vendor/semc/shakira/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
vendor/semc/shakira/proprietary/libmmipl.so:system/lib/libmmipl.so

## OMX proprietaries
PRODUCT_COPY_FILES += \
vendor/semc/shakira/proprietary/libmm-adspsvc.so:system/lib/libmm-adspsvc.so \
vendor/semc/shakira/proprietary/libOmxAacDec.so:system/lib/libOmxAacDec.so \
vendor/semc/shakira/proprietary/libOmxAmrRtpDec.so:system/lib/libOmxAmrRtpDec.so \
vendor/semc/shakira/proprietary/libOmxH264Dec.so:system/lib/libOmxH264Dec.so \
vendor/semc/shakira/proprietary/libOmxQcelpDec.so:system/lib/libOmxQcelpDec.so \
vendor/semc/shakira/proprietary/libOmxAacEnc.so:system/lib/libOmxAacEnc.so \
vendor/semc/shakira/proprietary/libOmxAmrwbDec.so:system/lib/libOmxAmrwbDec.so \
vendor/semc/shakira/proprietary/libOmxMp3Dec.so:system/lib/libOmxMp3Dec.so \
vendor/semc/shakira/proprietary/libOmxVidEnc.so:system/lib/libOmxVidEnc.so \
vendor/semc/shakira/proprietary/libOmxAmrDec.so:system/lib/libOmxAmrDec.so \
vendor/semc/shakira/proprietary/libOmxEvrcDec.so:system/lib/libOmxEvrcDec.so \
vendor/semc/shakira/proprietary/libOmxMpeg4Dec.so:system/lib/libOmxMpeg4Dec.so \
vendor/semc/shakira/proprietary/libOmxWmaDec.so:system/lib/libOmxWmaDec.so \
vendor/semc/shakira/proprietary/libOmxAmrEnc.so:system/lib/libOmxAmrEnc.so \
vendor/semc/shakira/proprietary/libOmxEvrcEnc.so:system/lib/libOmxEvrcEnc.so \
vendor/semc/shakira/proprietary/libOmxQcelp13Enc.so:system/lib/libOmxQcelp13Enc.so \
vendor/semc/shakira/proprietary/libOmxWmvDec.so:system/lib/libOmxWmvDec.so

## FIRMWARE
PRODUCT_COPY_FILES += \
vendor/semc/shakira/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
vendor/semc/shakira/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
vendor/semc/shakira/proprietary/fm_rx_init_1273.1.bts:system/etc/firmware/fm_rx_init_1273.1.bts \
vendor/semc/shakira/proprietary/fm_rx_init_1273.2.bts:system/etc/firmware/fm_rx_init_1273.2.bts \
vendor/semc/shakira/proprietary/fm_tx_init_1273.1.bts:system/etc/firmware/fm_tx_init_1273.1.bts \
vendor/semc/shakira/proprietary/fm_tx_init_1273.2.bts:system/etc/firmware/fm_tx_init_1273.2.bts \
vendor/semc/shakira/proprietary/fmc_init_1273.1.bts:system/etc/firmware/fmc_init_1273.1.bts \
vendor/semc/shakira/proprietary/fmc_init_1273.2.bts:system/etc/firmware/fmc_init_1273.2.bts \
vendor/semc/shakira/proprietary/TIInit_7.2.31.bts:system/etc/firmware/TIInit_7.2.31.bts 

## SE Sensors
PRODUCT_COPY_FILES += \
vendor/semc/shakira/proprietary/sensors.default.so:system/lib/hw/sensors.shakira.so
//vendor/semc/shakira/proprietary/copybit.msm7k.so:system/lib/hw/copybit.shakira.so

## WIFI & BT TI1271
PRODUCT_COPY_FILES += \
vendor/semc/shakira/proprietary/hciattach:system/bin/hciattach \
vendor/semc/shakira/proprietary/tiwlan.ini:system/etc/wifi/tiwlan.ini \
vendor/semc/shakira/proprietary/tiwlan_firmware.bin:system/etc/wifi/tiwlan_firmware.bin

## Adreno 200 files
PRODUCT_COPY_FILES += \
vendor/semc/shakira/proprietary/libgsl.so:system/lib/libgsl.so \
vendor/semc/shakira/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
vendor/semc/shakira/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
vendor/semc/shakira/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
vendor/semc/shakira/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so

## Other libraries and proprietary binaries
PRODUCT_COPY_FILES += \
vendor/semc/shakira/proprietary/libaudioeq.so:obj/lib/libaudioeq.so \
vendor/semc/shakira/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
vendor/semc/shakira/proprietary/sensors.conf:system/etc/sensors.conf \
vendor/semc/shakira/proprietary/sensors.default.so:system/lib/hw/sensors.shakira.so \
vendor/semc/shakira/proprietary/akmd2:system/bin/akmd2 

#offline charging animation
PRODUCT_COPY_FILES += \
vendor/semc/shakira/proprietary/chargemon:system/bin/charger \
vendor/semc/shakira/proprietary/libmiscta.so:system/lib/libmiscta.so \
vendor/semc/shakira/proprietary/semc_chargalg:system/bin/semc_chargalg \
vendor/semc/shakira/proprietary/updatemiscta:system/bin/updatemiscta 


