# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/zeusc/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/semc/zeusc/proprietary/lib/libcamera.so:obj/lib/libcamera.so

PRODUCT_COPY_FILES += \
    vendor/semc/zeusc/proprietary//system/usr/keylayout/atdaemon.kl:system//system/usr/keylayout/atdaemon.kl \
    vendor/semc/zeusc/proprietary//system/usr/keylayout/AVRCP.kl:system//system/usr/keylayout/AVRCP.kl \
    vendor/semc/zeusc/proprietary//system/usr/keylayout/keypad-game-zeus.kl:system//system/usr/keylayout/keypad-game-zeus.kl \
    vendor/semc/zeusc/proprietary//system/usr/keylayout/keypad-phone-zeus.kl:system//system/usr/keylayout/keypad-phone-zeus.kl \
    vendor/semc/zeusc/proprietary//system/usr/keylayout/keypad-pmic-zeus.kl:system//system/usr/keylayout/keypad-pmic-zeus.kl \
    vendor/semc/zeusc/proprietary//system/usr/keylayout/keypad-zeus.kl:system//system/usr/keylayout/keypad-zeus.kl \
    vendor/semc/zeusc/proprietary//system/usr/keylayout/qwerty.kl:system//system/usr/keylayout/qwerty.kl \
    vendor/semc/zeusc/proprietary//system/usr/keylayout/simple_remote.kl:system//system/usr/keylayout/simple_remote.kl \
    vendor/semc/zeusc/proprietary//system/usr/keychars/qwerty.kcm.bin:system//system/usr/keychars/qwerty.kcm.bin \
    vendor/semc/zeusc/proprietary//system/usr/keychars/qwerty2.kcm.bin:system//system/usr/keychars/qwerty2.kcm.bin \
    vendor/semc/zeusc/proprietary//system/usr/keychars/zeus-keypad.kcm.bin:system//system/usr/keychars/zeus-keypad.kcm.bin \
    vendor/semc/zeusc/proprietary//system/usr/keychars/zeus-keypad.kcm.bin:system//system/usr/keychars/zeus-keypad.kcm.bin \
    vendor/semc/zeusc/proprietary//system/bin/lidswitchd:system//system/bin/lidswitchd \
    vendor/semc/zeusc/proprietary//system/bin/port-bridge:system//system/bin/port-bridge \
    vendor/semc/zeusc/proprietary//system/bin/qmuxd:system//system/bin/qmuxd \
    vendor/semc/zeusc/proprietary//system/lib/libauth.so:system//system/lib/libauth.so \
    vendor/semc/zeusc/proprietary//system/lib/libcm.so:system//system/lib/libcm.so \
    vendor/semc/zeusc/proprietary//system/lib/libdiag.so:system//system/lib/libdiag.so \
    vendor/semc/zeusc/proprietary//system/lib/libdll.so:system//system/lib/libdll.so \
    vendor/semc/zeusc/proprietary//system/lib/libdsm.so:system//system/lib/libdsm.so \
    vendor/semc/zeusc/proprietary//system/lib/libdss.so:system//system/lib/libdss.so \
    vendor/semc/zeusc/proprietary//system/lib/libgsdi_exp.so:system//system/lib/libgsdi_exp.so \
    vendor/semc/zeusc/proprietary//system/lib/libgstk_exp.so:system//system/lib/libgstk_exp.so \
    vendor/semc/zeusc/proprietary//system/lib/libmmgsdilib.so:system//system/lib/libmmgsdilib.so \
    vendor/semc/zeusc/proprietary//system/lib/libnv.so:system//system/lib/libnv.so \
    vendor/semc/zeusc/proprietary//system/lib/liboem_rapi.so:system//system/lib/liboem_rapi.so \
    vendor/semc/zeusc/proprietary//system/lib/liboncrpc.so:system//system/lib/liboncrpc.so \
    vendor/semc/zeusc/proprietary//system/lib/libpbmlib.so:system//system/lib/libpbmlib.so \
    vendor/semc/zeusc/proprietary//system/lib/libqmi.so:system//system/lib/libqmi.so \
    vendor/semc/zeusc/proprietary//system/lib/libqueue.so:system//system/lib/libqueue.so \
    vendor/semc/zeusc/proprietary//system/lib/libuim.so:system//system/lib/libuim.so \
    vendor/semc/zeusc/proprietary//system/lib/libreference-ril.so:system//system/lib/libreference-ril.so \
    vendor/semc/zeusc/proprietary//system/lib/libril.so:system//system/lib/libril.so \
    vendor/semc/zeusc/proprietary//system/lib/libril-qc-1.so:system//system/lib/libril-qc-1.so \
    vendor/semc/zeusc/proprietary//system/lib/libwms.so:system//system/lib/libwms.so \
    vendor/semc/zeusc/proprietary//system/lib/libwmsts.so:system//system/lib/libwmsts.so \
    vendor/semc/zeusc/proprietary//system/etc/permissions/android.hardware.camera.front.xml:system//system/etc/permissions/android.hardware.camera.front.xml \
    vendor/semc/zeusc/proprietary//system/lib/liboemcamera.so:system//system/lib/liboemcamera.so \
    vendor/semc/zeusc/proprietary//system/lib/libmmjpeg.so:system//system/lib/libmmjpeg.so \
    vendor/semc/zeusc/proprietary//system/lib/libmmipl.so:system//system/lib/libmmipl.so \
    vendor/semc/zeusc/proprietary//system/lib/libcamera.so:system//system/lib/libcamera.so \
    vendor/semc/zeusc/proprietary//system/lib/libopencore_common.so:system//system/lib/libopencore_common.so \
    vendor/semc/zeusc/proprietary//system/bin/drmserver:system//system/bin/drmserver \
    vendor/semc/zeusc/proprietary//system/bin/drmioserver:system//system/bin/drmioserver \
    vendor/semc/zeusc/proprietary//system/etc/firmware/bcm4329.hcd:system//system/etc/firmware/bcm4329.hcd \
    vendor/semc/zeusc/proprietary//system/etc/firmware/fw_bcm4329.bin:system//system/etc/firmware/fw_bcm4329.bin \
    vendor/semc/zeusc/proprietary//system/etc/firmware/fw_bcm4329_apsta.bin:system//system/etc/firmware/fw_bcm4329_apsta.bin \
    vendor/semc/zeusc/proprietary//system/etc/firmware/vidc_720p_command_control.fw:system//system/etc/firmware/vidc_720p_command_control.fw \
    vendor/semc/zeusc/proprietary//system/etc/firmware/vidc_720p_h263_dec_mc.fw:system//system/etc/firmware/vidc_720p_h263_dec_mc.fw \
    vendor/semc/zeusc/proprietary//system/etc/firmware/vidc_720p_h264_dec_mc.fw:system//system/etc/firmware/vidc_720p_h264_dec_mc.fw \
    vendor/semc/zeusc/proprietary//system/etc/firmware/vidc_720p_h264_enc_mc.fw:system//system/etc/firmware/vidc_720p_h264_enc_mc.fw \
    vendor/semc/zeusc/proprietary//system/etc/firmware/vidc_720p_mp4_dec_mc.fw:system//system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
    vendor/semc/zeusc/proprietary//system/etc/firmware/vidc_720p_mp4_enc_mc.fw:system//system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
    vendor/semc/zeusc/proprietary//system/etc/firmware/vidc_720p_vc1_dec_mc.fw:system//system/etc/firmware/vidc_720p_vc1_dec_mc.fw \
    vendor/semc/zeusc/proprietary//system/etc/firmware/yamato_pfp.fw:system//system/etc/firmware/yamato_pfp.fw \
    vendor/semc/zeusc/proprietary//system/etc/firmware/yamato_pm4.fw:system//system/etc/firmware/yamato_pm4.fw \
    vendor/semc/zeusc/proprietary//system/etc/wifi/calibration:system//system/etc/wifi/calibration \
    vendor/semc/zeusc/proprietary//system/etc/wifi/wpa_supplicant.conf:system//system/etc/wifi/wpa_supplicant.conf \
    vendor/semc/zeusc/proprietary//system/bin/brcm_patchram_plus:system//system/bin/brcm_patchram_plus \
    vendor/semc/zeusc/proprietary//system/lib/libaudioalsa.so:system//system/lib/libaudioalsa.so \
    vendor/semc/zeusc/proprietary//system/lib/libaudioalsa.so:system//system/lib/libaudioalsa.so \
    vendor/semc/zeusc/proprietary//system/etc/sensors.conf:system//system/etc/sensors.conf \
    vendor/semc/zeusc/proprietary//system/etc/vold.fstab:system//system/etc/vold.fstab \
    vendor/semc/zeusc/proprietary//system/lib/hw/sensors.default.so:system//system/lib/hw/sensors.default.so \
    vendor/semc/zeusc/proprietary//system/bin/akmd8975:system//system/bin/akmd8975 \
    vendor/semc/zeusc/proprietary//system/bin/chargemon:system//system/bin/chargemon \
    vendor/semc/zeusc/proprietary//system/lib/libmiscta.so:system//system/lib/libmiscta.so \
    vendor/semc/zeusc/proprietary//system/lib/libgsl.so/libgsl.so:system//system/lib/libgsl.so/libgsl.so \
    vendor/semc/zeusc/proprietary//system/lib/egl/libGLESv1_CM_adreno200.so:system//system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/semc/zeusc/proprietary//system/lib/egl/libq3dtools_adreno200.so:system//system/lib/egl/libq3dtools_adreno200.so \
    vendor/semc/zeusc/proprietary//system/lib/egl/libEGL_adreno200.so:system//system/lib/egl/libEGL_adreno200.so \
    vendor/semc/zeusc/proprietary//system/lib/egl/libGLESv2_adreno200.so:system//system/lib/egl/libGLESv2_adreno200.so \
    vendor/semc/zeusc/proprietary//system/etc/permissions/com.playstation.playstationcertified.xml:system//system/etc/permissions/com.playstation.playstationcertified.xml \
    vendor/semc/zeusc/proprietary//system/etc/permissions/com.sonyericsson.android.xperiaplaycertified.xml:system//system/etc/permissions/com.sonyericsson.android.xperiaplaycertified.xml \
    vendor/semc/zeusc/proprietary//system/etc/permissions/com.sony.android.playstationcertified.xml:system//system/etc/permissions/com.sony.android.playstationcertified.xml \
    vendor/semc/zeusc/proprietary//system/framework/com.playstation.playstationcertified.jar:system//system/framework/com.playstation.playstationcertified.jar \
    vendor/semc/zeusc/proprietary//system/framework/playstationcertified.jar:system//system/framework/playstationcertified.jar \
    vendor/semc/zeusc/proprietary//system/framework/xperiaplaycertified.jar:system//system/framework/xperiaplaycertified.jar \
    vendor/semc/zeusc/proprietary//system/app/com.sonyericsson.androidapp.storefront.apk:system//system/app/com.sonyericsson.androidapp.storefront.apk \
    vendor/semc/zeusc/proprietary//system/app/preinstalledservice.apk:system//system/app/preinstalledservice.apk \
    vendor/semc/zeusc/proprietary//system/lib/librsasigner.so:system//system/lib/librsasigner.so
