# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/es209ra/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/semc/es209ra/proprietary/lib/libcamera.so:obj/lib/libcamera.so

PRODUCT_COPY_FILES += \
    vendor/semc/es209ra/proprietary//system/usr/keylayout/es209ra_keypad.kl:system//system/usr/keylayout/es209ra_keypad.kl \
    vendor/semc/es209ra/proprietary//system/usr/keylayout/es209ra_handset.kl:system//system/usr/keylayout/es209ra_handset.kl \
    vendor/semc/es209ra/proprietary//system/usr/keychars/es209ra_keypad.kcm.bin:system//system/usr/keychars/es209ra_keypad.kcm.bin \
    vendor/semc/es209ra/proprietary//system/lib/libril.so:system//system/lib/libril.so \
    vendor/semc/es209ra/proprietary//system/bin/port-bridge:system//system/bin/port-bridge \
    vendor/semc/es209ra/proprietary//system/bin/qmuxd:system//system/bin/qmuxd \
    vendor/semc/es209ra/proprietary//system/lib/libauth.so:system//system/lib/libauth.so \
    vendor/semc/es209ra/proprietary//system/lib/libcm.so:system//system/lib/libcm.so \
    vendor/semc/es209ra/proprietary//system/lib/libdiag.so:system//system/lib/libdiag.so \
    vendor/semc/es209ra/proprietary//system/lib/libdll.so:system//system/lib/libdll.so \
    vendor/semc/es209ra/proprietary//system/lib/libdsm.so:system//system/lib/libdsm.so \
    vendor/semc/es209ra/proprietary//system/lib/libdss.so:system//system/lib/libdss.so \
    vendor/semc/es209ra/proprietary//system/lib/libgsdi_exp.so:system//system/lib/libgsdi_exp.so \
    vendor/semc/es209ra/proprietary//system/lib/libgstk_exp.so:system//system/lib/libgstk_exp.so \
    vendor/semc/es209ra/proprietary//system/lib/libmmgsdilib.so:system//system/lib/libmmgsdilib.so \
    vendor/semc/es209ra/proprietary//system/lib/libnv.so:system//system/lib/libnv.so \
    vendor/semc/es209ra/proprietary//system/lib/liboem_rapi.so:system//system/lib/liboem_rapi.so \
    vendor/semc/es209ra/proprietary//system/lib/liboncrpc.so:system//system/lib/liboncrpc.so \
    vendor/semc/es209ra/proprietary//system/lib/libpbmlib.so:system//system/lib/libpbmlib.so \
    vendor/semc/es209ra/proprietary//system/lib/libqmi.so:system//system/lib/libqmi.so \
    vendor/semc/es209ra/proprietary//system/lib/libqueue.so:system//system/lib/libqueue.so \
    vendor/semc/es209ra/proprietary//system/lib/libuim.so:system//system/lib/libuim.so \
    vendor/semc/es209ra/proprietary//system/lib/libril-qc-1.so:system//system/lib/libril-qc-1.so \
    vendor/semc/es209ra/proprietary//system/lib/libwms.so:system//system/lib/libwms.so \
    vendor/semc/es209ra/proprietary//system/lib/libwmsts.so:system//system/lib/libwmsts.so \
    vendor/semc/es209ra/proprietary//system/lib/liboemcamera.so:system//system/lib/liboemcamera.so \
    vendor/semc/es209ra/proprietary//system/lib/libmmjpeg.so:system//system/lib/libmmjpeg.so \
    vendor/semc/es209ra/proprietary//system/lib/libmmipl.so:system//system/lib/libmmipl.so \
    vendor/semc/es209ra/proprietary//system/lib/libcamera.so:system//system/lib/libcamera.so \
    vendor/semc/es209ra/proprietary//system/lib/libopencore_common.so:system//system/lib/libopencore_common.so \
    vendor/semc/es209ra/proprietary//system/etc/firmware/yamato_pfp.fw:system//system/etc/firmware/yamato_pfp.fw \
    vendor/semc/es209ra/proprietary//system/etc/firmware/yamato_pm4.fw:system//system/etc/firmware/yamato_pm4.fw \
    vendor/semc/es209ra/proprietary//system/etc/firmware/camfirm.bin:system//system/etc/firmware/camfirm.bin \
    vendor/semc/es209ra/proprietary//system/lib/modules/athwlan.bin.z77:system//system/lib/modules/athwlan.bin.z77 \
    vendor/semc/es209ra/proprietary//system/lib/modules/data.patch.hw2_0.bin:system//system/lib/modules/data.patch.hw2_0.bin \
    vendor/semc/es209ra/proprietary//system/bin/wlan_mac:system//system/bin/wlan_mac \
    vendor/semc/es209ra/proprietary//system/bin/wlan_tool:system//system/bin/wlan_tool \
    vendor/semc/es209ra/proprietary//system/bin/hci_qcomm_init:system//system/bin/hci_qcomm_init \
    vendor/semc/es209ra/proprietary//system/bin/hciattach:system//system/bin/hciattach \
    vendor/semc/es209ra/proprietary//system/lib/libgsl.so/libgsl.so:system//system/lib/libgsl.so/libgsl.so \
    vendor/semc/es209ra/proprietary//system/lib/egl/libGLESv1_CM_adreno200.so:system//system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/semc/es209ra/proprietary//system/lib/egl/libq3dtools_adreno200.so:system//system/lib/egl/libq3dtools_adreno200.so \
    vendor/semc/es209ra/proprietary//system/lib/egl/libEGL_adreno200.so:system//system/lib/egl/libEGL_adreno200.so \
    vendor/semc/es209ra/proprietary//system/lib/egl/libGLESv2_adreno200.so:system//system/lib/egl/libGLESv2_adreno200.so \
    vendor/semc/es209ra/proprietary//system/etc/vold.fstab:system//system/etc/vold.fstab \
    vendor/semc/es209ra/proprietary//system/etc/sensors.conf:system//system/etc/sensors.conf \
    vendor/semc/es209ra/proprietary//system/bin/akmd2:system//system/bin/akmd2 \
    vendor/semc/es209ra/proprietary//system/bin/chargemon:system//system/bin/chargemon \
    vendor/semc/es209ra/proprietary//system/bin/updatemiscta:system//system/bin/updatemiscta \
    vendor/semc/es209ra/proprietary//system/lib/libmiscta.so:system//system/lib/libmiscta.so \
    vendor/semc/es209ra/proprietary//system/lib/hw/copybit.qsd8k.so:system//system/lib/hw/copybit.qsd8k.so \
    vendor/semc/es209ra/proprietary//system/lib/hw/sensors.default.so:system//system/lib/hw/sensors.default.so \
    vendor/semc/es209ra/proprietary//system/lib/hw/gralloc.es209ra.so:system//system/lib/hw/gralloc.es209ra.so \
    vendor/semc/es209ra/proprietary/OMX:system/OMX \
    vendor/semc/es209ra/proprietary//system/lib/hw/libOmxVdec.so:system//system/lib/hw/libOmxVdec.so \
    vendor/semc/es209ra/proprietary//system/lib/hw/libstagefrighthw.so:system//system/lib/hw/libstagefrighthw.so
