# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/semc/fuji/proprietary/lib/libmmjpeg.so:obj/lib/libmmjpeg.so

# This file is generated by device/semc/fuji/setup-makefiles.sh

PRODUCT_COPY_FILES := \
    vendor/semc/fuji/proprietary/lib/libals.so:system/lib/libals.so \
    vendor/semc/fuji/proprietary/lib/libcald_client.so:system/lib/libcald_client.so \
    vendor/semc/fuji/proprietary/lib/libcald_hal.so:system/lib/libcald_hal.so \
    vendor/semc/fuji/proprietary/lib/libcald_imageutil.so:system/lib/libcald_imageutil.so \
    vendor/semc/fuji/proprietary/lib/libcald_pal.so:system/lib/libcald_pal.so \
    vendor/semc/fuji/proprietary/lib/libcald_server.so:system/lib/libcald_server.so \
    vendor/semc/fuji/proprietary/lib/libcald_util.so:system/lib/libcald_util.so \
    vendor/semc/fuji/proprietary/lib/libcamera.so:system/lib/libcamera.so \
    vendor/semc/fuji/proprietary/lib/libcamera_clientsemc.so:system/lib/libcamera_clientsemc.so \
    vendor/semc/fuji/proprietary/lib/libcameraextensionjni.so:system/lib/libcameraextensionjni.so \
    vendor/semc/fuji/proprietary/lib/libcameraextensionservice.so:system/lib/libcameraextensionservice.so \
    vendor/semc/fuji/proprietary/lib/libcameraextensionclient.so:system/lib/libcameraextensionclient.so \
    vendor/semc/fuji/proprietary/lib/libcameralight.so:system/lib/libcameralight.so \
    vendor/semc/fuji/proprietary/lib/libface.so:system/lib/libface.so \
    vendor/semc/fuji/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/semc/fuji/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/semc/fuji/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/semc/fuji/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
    vendor/semc/fuji/proprietary/lib/libmmstereo.so:system/lib/libmmstereo.so \
    vendor/semc/fuji/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/semc/fuji/proprietary/usr/semc/camera/KMO13BS0_BU6456.dat:system/usr/semc/camera/KMO13BS0_BU6456.dat \
    vendor/semc/fuji/proprietary/usr/semc/camera/APT01BM0.dat:system/usr/semc/camera/APT01BM0.dat \
    vendor/semc/fuji/proprietary/usr/semc/camera/KMO13BS0.dat:system/usr/semc/camera/KMO13BS0.dat \
    vendor/semc/fuji/proprietary/usr/semc/camera/SOI13BS0.dat:system/usr/semc/camera/SOI13BS0.dat \
    vendor/semc/fuji/proprietary/usr/semc/camera/LM3560_05_flash.dat:system/usr/semc/camera/LM3560_05_flash.dat \
    vendor/semc/fuji/proprietary/usr/semc/camera/KMO13BS0_IMX091.dat:system/usr/semc/camera/KMO13BS0_IMX091.dat \
    vendor/semc/fuji/proprietary/usr/semc/camera/SOI13BS0_BU6456.dat:system/usr/semc/camera/SOI13BS0_BU6456.dat \
    vendor/semc/fuji/proprietary/usr/semc/camera/STW01BM0.dat:system/usr/semc/camera/STW01BM0.dat \
    vendor/semc/fuji/proprietary/usr/semc/camera/SOI13BS0_IMX091.dat:system/usr/semc/camera/SOI13BS0_IMX091.dat \
    vendor/semc/fuji/proprietary/usr/idc/clearpad.idc:system/usr/idc/clearpad.idc \
    vendor/semc/fuji/proprietary/usr/keylayout/keypad-pmic-fuji.kl:system/usr/keylayout/keypad-pmic-fuji.kl \
    vendor/semc/fuji/proprietary/usr/keylayout/usb_mouse.kl:system/usr/keylayout/usb_mouse.kl \
    vendor/semc/fuji/proprietary/usr/keylayout/simple_remote.kl:system/usr/keylayout/simple_remote.kl \
    vendor/semc/fuji/proprietary/usr/keylayout/us104-keyboard.kl:system/usr/keylayout/us104-keyboard.kl \
    vendor/semc/fuji/proprietary/usr/keylayout/pmic8058_pwrkey.kl:system/usr/keylayout/pmic8058_pwrkey.kl \
    vendor/semc/fuji/proprietary/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
    vendor/semc/fuji/proprietary/usr/keylayout/gpio-key.kl:system/usr/keylayout/gpio-key.kl \
    vendor/semc/fuji/proprietary/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
    vendor/semc/fuji/proprietary/usr/keylayout/fuji-keypad.kl:system/usr/keylayout/fuji-keypad.kl \
    vendor/semc/fuji/proprietary/usr/keylayout/atdaemon.kl:system/usr/keylayout/atdaemon.kl \
    vendor/semc/fuji/proprietary/usr/keylayout/clearpad.kl:system/usr/keylayout/clearpad.kl \
    vendor/semc/fuji/proprietary/etc/firmware/wlan/volans:system/etc/firmware/wlan/volans \
    vendor/semc/fuji/proprietary/etc/firmware/wlan/volans/WCN1314_qcom_fw.bin:system/etc/firmware/wlan/volans/WCN1314_qcom_fw.bin \
    vendor/semc/fuji/proprietary/etc/firmware/wlan/volans/WCN1314_qcom_cfg.ini:system/etc/firmware/wlan/volans/WCN1314_qcom_cfg.ini \
    vendor/semc/fuji/proprietary/etc/firmware/wlan/volans/WCN1314_cfg.dat:system/etc/firmware/wlan/volans/WCN1314_cfg.dat \
    vendor/semc/fuji/proprietary/etc/firmware/fw_bcm4330b1.bin:system/etc/firmware/fw_bcm4330b1.bin \
    vendor/semc/fuji/proprietary/etc/firmware/fw_bcm4330b2.bin:system/etc/firmware/fw_bcm4330b2.bin \
    vendor/semc/fuji/proprietary/etc/firmware/BCM4330.hcd:system/etc/firmware/BCM4330.hcd \
    vendor/semc/fuji/proprietary/etc/firmware/fw_bcm4330b2_apsta.bin:system/etc/firmware/fw_bcm4330b2_apsta.bin \
    vendor/semc/fuji/proprietary/etc/firmware/fw_bcm4330b1_apsta.bin:system/etc/firmware/fw_bcm4330b1_apsta.bin \
    vendor/semc/fuji/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/semc/fuji/proprietary/etc/firmware/modem.b00:system/etc/firmware/modem.b00 \
    vendor/semc/fuji/proprietary/etc/firmware/modem.b01:system/etc/firmware/modem.b01 \
    vendor/semc/fuji/proprietary/etc/firmware/modem.b02:system/etc/firmware/modem.b02 \
    vendor/semc/fuji/proprietary/etc/firmware/modem.b03:system/etc/firmware/modem.b03 \
    vendor/semc/fuji/proprietary/etc/firmware/modem.b04:system/etc/firmware/modem.b04 \
    vendor/semc/fuji/proprietary/etc/firmware/modem.b05:system/etc/firmware/modem.b05 \
    vendor/semc/fuji/proprietary/etc/firmware/modem.b06:system/etc/firmware/modem.b06 \
    vendor/semc/fuji/proprietary/etc/firmware/modem.b07:system/etc/firmware/modem.b07 \
    vendor/semc/fuji/proprietary/etc/firmware/modem.b08:system/etc/firmware/modem.b08 \
    vendor/semc/fuji/proprietary/etc/firmware/modem.b09:system/etc/firmware/modem.b09 \
    vendor/semc/fuji/proprietary/etc/firmware/modem.b10:system/etc/firmware/modem.b10 \
    vendor/semc/fuji/proprietary/etc/firmware/modem.mdt:system/etc/firmware/modem.mdt \
    vendor/semc/fuji/proprietary/etc/firmware/tzexec.b00:system/etc/firmware/tzexec.b00 \
    vendor/semc/fuji/proprietary/etc/firmware/tzexec.b01:system/etc/firmware/tzexec.b01 \
    vendor/semc/fuji/proprietary/etc/firmware/tzexec.b02:system/etc/firmware/tzexec.b02 \
    vendor/semc/fuji/proprietary/etc/firmware/tzexec.mdt:system/etc/firmware/tzexec.mdt \
    vendor/semc/fuji/proprietary/etc/firmware/q6.b00:system/etc/firmware/q6.b00 \
    vendor/semc/fuji/proprietary/etc/firmware/q6.b01:system/etc/firmware/q6.b01 \
    vendor/semc/fuji/proprietary/etc/firmware/q6.b02:system/etc/firmware/q6.b02 \
    vendor/semc/fuji/proprietary/etc/firmware/q6.b03:system/etc/firmware/q6.b03 \
    vendor/semc/fuji/proprietary/etc/firmware/q6.b04:system/etc/firmware/q6.b04 \
    vendor/semc/fuji/proprietary/etc/firmware/q6.b05:system/etc/firmware/q6.b05 \
    vendor/semc/fuji/proprietary/etc/firmware/q6.b06:system/etc/firmware/q6.b06 \
    vendor/semc/fuji/proprietary/etc/firmware/q6.b07:system/etc/firmware/q6.b07 \
    vendor/semc/fuji/proprietary/etc/firmware/q6.mdt:system/etc/firmware/q6.mdt \
    vendor/semc/fuji/proprietary/etc/firmware/touch_module_id_0x01.img:system/etc/firmware/touch_module_id_0x01.img \
    vendor/semc/fuji/proprietary/etc/firmware/touch_module_id_0x02.img:system/etc/firmware/touch_module_id_0x02.img \
    vendor/semc/fuji/proprietary/etc/firmware/touch_module_id_0x11.img:system/etc/firmware/touch_module_id_0x11.img \
    vendor/semc/fuji/proprietary/etc/firmware/touch_module_id_0x12.img:system/etc/firmware/touch_module_id_0x12.img \
    vendor/semc/fuji/proprietary/etc/firmware/touch_module_id_0x13.img:system/etc/firmware/touch_module_id_0x13.img \
    vendor/semc/fuji/proprietary/etc/firmware/touch_module_id_0x14.img:system/etc/firmware/touch_module_id_0x14.img \
    vendor/semc/fuji/proprietary/etc/firmware/touch_module_id_0x16.img:system/etc/firmware/touch_module_id_0x16.img \
    vendor/semc/fuji/proprietary/etc/firmware/touch_module_id_0x1b.img:system/etc/firmware/touch_module_id_0x1b.img \
    vendor/semc/fuji/proprietary/etc/firmware/touch_module_id_0x1c.img:system/etc/firmware/touch_module_id_0x1c.img \
    vendor/semc/fuji/proprietary/etc/firmware/touch_module_id_0x1d.img:system/etc/firmware/touch_module_id_0x1d.img \
    vendor/semc/fuji/proprietary/etc/firmware/touch_module_id_0x20.img:system/etc/firmware/touch_module_id_0x20.img \
    vendor/semc/fuji/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/semc/fuji/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/semc/fuji/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/semc/fuji/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/semc/fuji/proprietary/etc/firmware/bq27520_fw-0507_filever-0115_proj-nozo_golden.bqfs:system/etc/firmware/bq27520_fw-0507_filever-0115_proj-nozo_golden.bqfs \
    vendor/semc/fuji/proprietary/etc/firmware/bq27520_fw-0507_filever-0115_proj-nozo_golden.dffs:system/etc/firmware/bq27520_fw-0507_filever-0115_proj-nozo_golden.dffs \
    vendor/semc/fuji/proprietary/etc/wifi/calibration:system/etc/wifi/calibration \
    vendor/semc/fuji/proprietary/etc/wifi/wpa_supplicant.conf:system/etc/wifi/wpa_supplicant.conf \
    vendor/semc/fuji/proprietary/etc/permissions/android.hardware.nfc.xml:system/etc/permissions/android.hardware.nfc.xml \
    vendor/semc/fuji/proprietary/etc/permissions/android.hardware.camera.front.xml:system/etc/permissions/android.hardware.camera.front.xml \
    vendor/semc/fuji/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/semc/fuji/proprietary/etc/sensors.conf:system/etc/sensors.conf \
    vendor/semc/fuji/proprietary/etc/vold.fstab:system/etc/vold.fstab \
    vendor/semc/fuji/proprietary/etc/flashled_calc_parameters.cfg:system/etc/flashled_calc_parameters.cfg \
    vendor/semc/fuji/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/semc/fuji/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/semc/fuji/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/semc/fuji/proprietary/lib/libmiscta.so:system/lib/libmiscta.so \
    vendor/semc/fuji/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/semc/fuji/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/semc/fuji/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/semc/fuji/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/semc/fuji/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/semc/fuji/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/semc/fuji/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/semc/fuji/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/semc/fuji/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/semc/fuji/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/semc/fuji/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/semc/fuji/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/semc/fuji/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/semc/fuji/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/semc/fuji/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/semc/fuji/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/semc/fuji/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/semc/fuji/proprietary/lib/hw/gps.msm8660.so:system/lib/hw/gps.msm8660.so \
    vendor/semc/fuji/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/semc/fuji/proprietary/lib/hw/lights.semc.so:system/lib/hw/lights.semc.so \
    vendor/semc/fuji/proprietary/lib/hw/gralloc.msm8660.so:system/lib/hw/gralloc.msm8660.so \
    vendor/semc/fuji/proprietary/bin/touchd:system/bin/touchd \
    vendor/semc/fuji/proprietary/bin/bq275xx_fwloader:system/bin/bq275xx_fwloader \
    vendor/semc/fuji/proprietary/bin/chargemon:system/bin/chargemon \
    vendor/semc/fuji/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/semc/fuji/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/semc/fuji/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/semc/fuji/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/semc/fuji/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/semc/fuji/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/semc/fuji/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/semc/fuji/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/semc/fuji/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so
