
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/urushi/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries

# Prebuilt kl keymaps
PRODUCT_COPY_FILES += \
vendor/semc/urushi/proprietary/qwerty.kcm.bin:system/usr/keychars/qwerty.kcm.bin \
vendor/semc/urushi/proprietary/qwerty2.kcm.bin:system/usr/keychars/qwerty2.kcm.bin \
vendor/semc/urushi/proprietary/atdaemon.kl:system/usr/keylayout/atdaemon.kl \
vendor/semc/urushi/proprietary/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
vendor/semc/urushi/proprietary/clearpad.kl:system/usr/keylayout/clearpad.kl \
vendor/semc/urushi/proprietary/msm_pmic_pwr_key.kl:system/usr/keylayout/msm_pmic_pwr_key.kl \
vendor/semc/urushi/proprietary/pm8058-keypad.kl:system/usr/keylayout/pm8058-keypad.kl \
vendor/semc/urushi/proprietary/qwerty.kl:system/usr/keylayout/qwerty.kl \
vendor/semc/urushi/proprietary/simple_remote.kl:system/usr/keylayout/simple_remote.kl


## RIL related stuff 
PRODUCT_COPY_FILES += \
vendor/semc/urushi/proprietary/libril.so:system/lib/libril.so \
vendor/semc/urushi/proprietary/port-bridge:system/bin/port-bridge \
vendor/semc/urushi/proprietary/qmuxd:system/bin/qmuxd \
vendor/semc/urushi/proprietary/libauth.so:system/lib/libauth.so \
vendor/semc/urushi/proprietary/libcm.so:system/lib/libcm.so \
vendor/semc/urushi/proprietary/libdiag.so:system/lib/libdiag.so \
vendor/semc/urushi/proprietary/libdll.so:system/lib/libdll.so \
vendor/semc/urushi/proprietary/libdsm.so:system/lib/libdsm.so \
vendor/semc/urushi/proprietary/libdss.so:system/lib/libdss.so \
vendor/semc/urushi/proprietary/libgsdi_exp.so:system/lib/libgsdi_exp.so \
vendor/semc/urushi/proprietary/libgstk_exp.so:system/lib/libgstk_exp.so \
vendor/semc/urushi/proprietary/libmmgsdilib.so:system/lib/libmmgsdilib.so \
vendor/semc/urushi/proprietary/libnv.so:system/lib/libnv.so \
vendor/semc/urushi/proprietary/liboem_rapi.so:system/lib/liboem_rapi.so \
vendor/semc/urushi/proprietary/liboncrpc.so:system/lib/liboncrpc.so \
vendor/semc/urushi/proprietary/libpbmlib.so:system/lib/libpbmlib.so \
vendor/semc/urushi/proprietary/libqmi.so:system/lib/libqmi.so \
vendor/semc/urushi/proprietary/libqueue.so:system/lib/libqueue.so \
vendor/semc/urushi/proprietary/libuim.so:system/lib/libuim.so \
vendor/semc/urushi/proprietary/libreference-ril.so:system/lib/libreference-ril.so \
vendor/semc/urushi/proprietary/libril-qc-1.so:system/lib/libril-qc-1.so \
vendor/semc/urushi/proprietary/libwms.so:system/lib/libwms.so \
vendor/semc/urushi/proprietary/libwmsts.so:system/lib/libwmsts.so \
vendor/semc/urushi/proprietary/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
vendor/semc/urushi/proprietary/libdsutils.so:system/lib/libdsutils.so \
vendor/semc/urushi/proprietary/libidl.so:system/lib/libidl.so \
vendor/semc/urushi/proprietary/libnetmgr.so:system/lib/libnetmgr.so \
vendor/semc/urushi/proprietary/libqdp.so:system/lib/libqdp.so \
vendor/semc/urushi/proprietary/netmgrd:system/bin/netmgrd

## Camera proprietaries
PRODUCT_COPY_FILES += \
vendor/semc/urushi/proprietary/liboemcamera.so:system/lib/liboemcamera.so \
vendor/semc/urushi/proprietary/libcamera.so:obj/lib/libcamera.so \
vendor/semc/urushi/proprietary/libcamera.so:system/lib/libcamera.so \
vendor/semc/urushi/proprietary/libcamera_clientsemc.so:system/lib/libcamera_clientsemc.so \
vendor/semc/urushi/proprietary/libopencore_common.so:system/lib/libopencore_common.so \
vendor/semc/urushi/proprietary/libmmjpeg.so:system/lib/libmmjpeg.so \
vendor/semc/urushi/proprietary/libmmipl.so:system/lib/libmmipl.so \
vendor/semc/urushi/proprietary/libcald_api.so:system/lib/libcald_api.so \
vendor/semc/urushi/proprietary/libcald_client.so:system/lib/libcald_client.so \
vendor/semc/urushi/proprietary/libcald_debugger.so:system/lib/libcald_debugger.so \
vendor/semc/urushi/proprietary/libcald_hal.so:system/lib/libcald_hal.so \
vendor/semc/urushi/proprietary/libcald_imageutil.so:system/lib/libcald_imageutil.so \
vendor/semc/urushi/proprietary/libcald_omxcamera.so:system/lib/libcald_omxcamera.so \
vendor/semc/urushi/proprietary/libcald_omxcamera_plugin.so:system/lib/libcald_omxcamera_plugin.so \
vendor/semc/urushi/proprietary/libcald_pal.so:system/lib/libcald_pal.so \
vendor/semc/urushi/proprietary/libcald_server.so:system/lib/libcald_server.so \
vendor/semc/urushi/proprietary/libcameraextensionclient.so:system/lib/libcameraextensionclient.so \
vendor/semc/urushi/proprietary/libcameraextensionjni.so:system/lib/libcameraextensionjni.so \
vendor/semc/urushi/proprietary/libcameraextensionservice.so:system/lib/libcameraextensionservice.so \
vendor/semc/urushi/proprietary/libface.so:system/lib/libface.so \
vendor/semc/urushi/proprietary/libgemini.so:system/lib/libgemini.so \
vendor/semc/urushi/proprietary/libcameralight.so:system/lib/libcameralight.so \
vendor/semc/urushi/proprietary/APT00YP0.dat:system/usr/semc/camera/APT00YP0.dat \
vendor/semc/urushi/proprietary/APT00YP0_MT9V144.dat:system/usr/semc/camera/APT00YP0_MT9V144.dat \
vendor/semc/urushi/proprietary/AS3676_00_flash.dat:system/usr/semc/camera/AS3676_00_flash.dat \
vendor/semc/urushi/proprietary/LGI08BN0.dat:system/usr/semc/camera/LGI08BN0.dat \
vendor/semc/urushi/proprietary/SOD08BN0.dat:system/usr/semc/camera/SOD08BN0.dat \
vendor/semc/urushi/proprietary/SOD08BN0_DW9714.dat:system/usr/semc/camera/SOD08BN0_DW9714.dat \
vendor/semc/urushi/proprietary/SOD08BN0_IMX073.dat:system/usr/semc/camera/SOD08BN0_IMX073.dat \
vendor/semc/urushi/proprietary/SOD08BN1.dat:system/usr/semc/camera/SOD08BN1.dat \
vendor/semc/urushi/proprietary/SOD08BN1_DW9714.dat:system/usr/semc/camera/SOD08BN1_DW9714.dat \
vendor/semc/urushi/proprietary/SOD08BN1_IMX105.dat:system/usr/semc/camera/SOD08BN1_IMX105.dat



## FIRMWARE
PRODUCT_COPY_FILES += \
vendor/semc/urushi/proprietary/bq27520_fw-0501_filever-0107_proj-hall_golden.bqfs:system/etc/firmware/bq27520_fw-0501_filever-0107_proj-hall_golden.bqfs \
vendor/semc/urushi/proprietary/bq27520_fw-0501_filever-0107_proj-hall_golden.dffs:system/etc/firmware/bq27520_fw-0501_filever-0107_proj-hall_golden.dffs \
vendor/semc/urushi/proprietary/fm_rx_init_1273.1.bts:system/etc/firmware/fm_rx_init_1273.1.bts \
vendor/semc/urushi/proprietary/fm_rx_init_1273.2.bts:system/etc/firmware/fm_rx_init_1273.2.bts \
vendor/semc/urushi/proprietary/fm_tx_init_1273.1.bts:system/etc/firmware/fm_tx_init_1273.1.bts \
vendor/semc/urushi/proprietary/fm_tx_init_1273.2.bts:system/etc/firmware/fm_tx_init_1273.2.bts \
vendor/semc/urushi/proprietary/fmc_init_1273.1.bts:system/etc/firmware/fmc_init_1273.1.bts \
vendor/semc/urushi/proprietary/fmc_init_1273.2.bts:system/etc/firmware/fmc_init_1273.2.bts \
vendor/semc/urushi/proprietary/TIInit_7.5.20.bts:system/etc/firmware/TIInit_7.5.20.bts \
vendor/semc/urushi/proprietary/TIInit_7.6.15.bts:system/etc/firmware/TIInit_7.6.15.bts \
vendor/semc/urushi/proprietary/vidc_720p_command_control.fw:system/etc/firmware/vidc_720p_command_control.fw \
vendor/semc/urushi/proprietary/vidc_720p_h263_dec_mc.fw:system/etc/firmware/vidc_720p_h263_dec_mc.fw \
vendor/semc/urushi/proprietary/vidc_720p_h264_dec_mc.fw:system/etc/firmware/vidc_720p_h264_dec_mc.fw \
vendor/semc/urushi/proprietary/vidc_720p_h264_enc_mc.fw:system/etc/firmware/vidc_720p_h264_enc_mc.fw \
vendor/semc/urushi/proprietary/vidc_720p_mp4_dec_mc.fw:system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
vendor/semc/urushi/proprietary/vidc_720p_mp4_enc_mc.fw:system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
vendor/semc/urushi/proprietary/vidc_720p_vc1_dec_mc.fw:system/etc/firmware/vidc_720p_vc1_dec_mc.fw \
vendor/semc/urushi/proprietary/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
vendor/semc/urushi/proprietary/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw 

## WIFI & BT TI1271
PRODUCT_COPY_FILES += \
vendor/semc/urushi/proprietary/hciattach:system/bin/hciattach \
vendor/semc/urushi/proprietary/init.qcom.bt.sh:system/etc/init.bt.sh \
vendor/semc/urushi/proprietary/tiwlan.ini:system/etc/wifi/tiwlan.ini \
vendor/semc/urushi/proprietary/tiwlan_firmware.bin:system/etc/wifi/tiwlan_firmware.bin \
vendor/semc/urushi/proprietary/tiwlan_ap.ini:system/etc/wifi/softap/tiwlan_ap.ini \
vendor/semc/urushi/proprietary/softap_firmware.bin:system/etc/wifi/softap/tiwlan_firmware_ap.bin \
vendor/semc/urushi/proprietary/nvimport:system/bin/nvimport


## Other libraries and proprietary binaries
PRODUCT_COPY_FILES += \
vendor/semc/urushi/proprietary/libaudioalsa.so:obj/lib/libaudioalsa.so \
vendor/semc/urushi/proprietary/libaudioalsa.so:system/lib/libaudioalsa.so \
vendor/semc/urushi/proprietary/libaudioeq.so:system/lib/libaudioeq.so \
vendor/semc/urushi/proprietary/als_curve.conf:system/etc/als_curve.conf \
vendor/semc/urushi/proprietary/vold.fstab:system/etc/vold.fstab \
vendor/semc/urushi/proprietary/sensors.conf:system/etc/sensors.conf \
vendor/semc/urushi/proprietary/sensors.default.so:system/lib/hw/sensors.semc.so \
vendor/semc/urushi/proprietary/bq275xx_fwloader:system/bin/bq275xx_fwloader \
vendor/semc/urushi/proprietary/akmd8975:system/bin/akmd8975

#offline charging animation
PRODUCT_COPY_FILES += \
vendor/semc/urushi/proprietary/chargemon:system/bin/chargemon \
vendor/semc/urushi/proprietary/libmiscta.so:system/lib/libmiscta.so

#Temporary GPS Fix untill we have 50001 gps
PRODUCT_COPY_FILES += \
vendor/semc/urushi/proprietary/gps.msm7x30.so:system/lib/hw/gps.semc.so

#touch
PRODUCT_COPY_FILES += \
vendor/semc/urushi/proprietary/touch_module_id_0x01.img:system/etc/firmware/touch_module_id_0x01.img \
vendor/semc/urushi/proprietary/touch_module_id_0x02.img:system/etc/firmware/touch_module_id_0x02.img \
vendor/semc/urushi/proprietary/touch_module_id_0x11.img:system/etc/firmware/touch_module_id_0x11.img 

## Adreno 200 files
PRODUCT_COPY_FILES += \
vendor/semc/urushi/proprietary/libgsl.so:system/lib/libgsl.so \
vendor/semc/urushi/proprietary/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
vendor/semc/urushi/proprietary/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
vendor/semc/urushi/proprietary/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
vendor/semc/urushi/proprietary/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so

#ANT*
PRODUCT_COPY_FILES += \
vendor/semc/urushi/proprietary/AntHalService.apk:system/app/AntHalService.apk \
vendor/semc/urushi/proprietary/com.dsi.ant.antradio_library.xml:system/etc/permissions/com.dsi.ant.antradio_library.xml \
vendor/semc/urushi/proprietary/com.dsi.ant.antradio_library.jar:system/framework/com.dsi.ant.antradio_library.jar \
vendor/semc/urushi/proprietary/libanthal.so:system/lib/libanthal.so

