# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/urushi/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/semc/urushi/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
    vendor/semc/urushi/proprietary/lib/libaudio.so:obj/lib/libaudio.so \
    vendor/semc/urushi/proprietary/lib/liba2dp.so:obj/lib/liba2dp.so \
    vendor/semc/urushi/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

PRODUCT_COPY_FILES += \
    vendor/semc/urushi/proprietary/usr/keychars/qwerty.kcm.bin:system/usr/keychars/qwerty.kcm.bin \
    vendor/semc/urushi/proprietary/usr/keylayout/atdaemon.kl:system/usr/keylayout/atdaemon.kl \
    vendor/semc/urushi/proprietary/usr/keylayout/clearpad.kl:system/usr/keylayout/clearpad.kl \
    vendor/semc/urushi/proprietary/usr/keylayout/AVRCP.kl:system/usr/keylayout/AVRCP.kl \
    vendor/semc/urushi/proprietary/usr/keylayout/msm_pmic_pwr_key.kl:system/usr/keylayout/msm_pmic_pwr_key.kl \
    vendor/semc/urushi/proprietary/usr/keylayout/pm8058-keypad.kl:system/usr/keylayout/pm8058-keypad.kl \
    vendor/semc/urushi/proprietary/usr/keylayout/qwerty.kl:system/usr/keylayout/qwerty.kl \
    vendor/semc/urushi/proprietary/usr/keylayout/simple_remote.kl:system/usr/keylayout/simple_remote.kl \
    vendor/semc/urushi/proprietary/usr/keychars/us104-keyboard.kcm.bin:system/usr/keychars/us104-keyboard.kcm.bin \
    vendor/semc/urushi/proprietary/usr/keylayout/us104-keyboard.kl:system/usr/keylayout/us104-keyboard.kl \
    vendor/semc/urushi/proprietary/usr/keylayout/usb_mouse.kl:system/usr/keylayout/usb_mouse.kl \
    vendor/semc/urushi/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/semc/urushi/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/semc/urushi/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/semc/urushi/proprietary/lib/libauth.so:system/lib/libauth.so \
    vendor/semc/urushi/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/semc/urushi/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/semc/urushi/proprietary/lib/libdll.so:system/lib/libdll.so \
    vendor/semc/urushi/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/semc/urushi/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/semc/urushi/proprietary/lib/libgsdi_exp.so:system/lib/libgsdi_exp.so \
    vendor/semc/urushi/proprietary/lib/libgstk_exp.so:system/lib/libgstk_exp.so \
    vendor/semc/urushi/proprietary/lib/libmmgsdilib.so:system/lib/libmmgsdilib.so \
    vendor/semc/urushi/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/semc/urushi/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
    vendor/semc/urushi/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/semc/urushi/proprietary/lib/libpbmlib.so:system/lib/libpbmlib.so \
    vendor/semc/urushi/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/semc/urushi/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/semc/urushi/proprietary/lib/libuim.so:system/lib/libuim.so \
    vendor/semc/urushi/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/semc/urushi/proprietary/lib/libril-qc-1.so:system/lib/libril-qc-1.so \
    vendor/semc/urushi/proprietary/lib/libwms.so:system/lib/libwms.so \
    vendor/semc/urushi/proprietary/lib/libwmsts.so:system/lib/libwmsts.so \
    vendor/semc/urushi/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/semc/urushi/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/semc/urushi/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/semc/urushi/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/semc/urushi/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/semc/urushi/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/semc/urushi/proprietary/etc/firmware/bq27520_fw-0507_filever-0112_proj-hall_golden.bqfs:system/etc/firmware/bq27520_fw-0507_filever-0112_proj-hall_golden.bqfs \
    vendor/semc/urushi/proprietary/etc/firmware/fm_rx_init_1273.1.bts:system/etc/firmware/fm_rx_init_1273.1.bts \
    vendor/semc/urushi/proprietary/etc/firmware/fm_rx_init_1273.2.bts:system/etc/firmware/fm_rx_init_1273.2.bts \
    vendor/semc/urushi/proprietary/etc/firmware/fm_tx_init_1273.1.bts:system/etc/firmware/fm_tx_init_1273.1.bts \
    vendor/semc/urushi/proprietary/etc/firmware/fm_tx_init_1273.2.bts:system/etc/firmware/fm_tx_init_1273.2.bts \
    vendor/semc/urushi/proprietary/etc/firmware/fmc_init_1273.1.bts:system/etc/firmware/fmc_init_1273.1.bts \
    vendor/semc/urushi/proprietary/etc/firmware/fmc_init_1273.2.bts:system/etc/firmware/fmc_init_1273.2.bts \
    vendor/semc/urushi/proprietary/etc/firmware/TIInit_7.5.20.bts:system/etc/firmware/TIInit_7.5.20.bts \
    vendor/semc/urushi/proprietary/etc/firmware/TIInit_7.6.15.bts:system/etc/firmware/TIInit_7.6.15.bts \
    vendor/semc/urushi/proprietary/etc/firmware/vidc_720p_command_control.fw:system/etc/firmware/vidc_720p_command_control.fw \
    vendor/semc/urushi/proprietary/etc/firmware/vidc_720p_h263_dec_mc.fw:system/etc/firmware/vidc_720p_h263_dec_mc.fw \
    vendor/semc/urushi/proprietary/etc/firmware/vidc_720p_h264_dec_mc.fw:system/etc/firmware/vidc_720p_h264_dec_mc.fw \
    vendor/semc/urushi/proprietary/etc/firmware/vidc_720p_h264_enc_mc.fw:system/etc/firmware/vidc_720p_h264_enc_mc.fw \
    vendor/semc/urushi/proprietary/etc/firmware/vidc_720p_mp4_dec_mc.fw:system/etc/firmware/vidc_720p_mp4_dec_mc.fw \
    vendor/semc/urushi/proprietary/etc/firmware/vidc_720p_mp4_enc_mc.fw:system/etc/firmware/vidc_720p_mp4_enc_mc.fw \
    vendor/semc/urushi/proprietary/etc/firmware/vidc_720p_vc1_dec_mc.fw:system/etc/firmware/vidc_720p_vc1_dec_mc.fw \
    vendor/semc/urushi/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/semc/urushi/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/semc/urushi/proprietary/bin/nvimport:system/bin/nvimport \
    vendor/semc/urushi/proprietary/bin/hciattach:system/bin/hciattach \
    vendor/semc/urushi/proprietary/etc/init.qcom.bt.sh:system/etc/init.qcom.bt.sh \
    vendor/semc/urushi/proprietary/etc/wifi/tiwlan.ini:system/etc/wifi/tiwlan.ini \
    vendor/semc/urushi/proprietary/etc/wifi/tiwlan_firmware.bin:system/etc/wifi/tiwlan_firmware.bin \
    vendor/semc/urushi/proprietary/etc/wifi/softap/tiwlan_ap.ini:system/etc/wifi/softap/tiwlan_ap.ini \
    vendor/semc/urushi/proprietary/etc/wifi/softap/tiwlan_firmware_ap.bin:system/etc/wifi/softap/tiwlan_firmware_ap.bin \
    vendor/semc/urushi/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/semc/urushi/proprietary/lib/hw/gralloc.semc.so:system/lib/hw/gralloc.semc.so \
    vendor/semc/urushi/proprietary/lib/hw/overlay.semc.so:system/lib/hw/overlay.semc.so \
    vendor/semc/urushi/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/semc/urushi/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/semc/urushi/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/semc/urushi/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/semc/urushi/proprietary/lib/liba2dp.so:system/lib/liba2dp.so \
    vendor/semc/urushi/proprietary/lib/libaudio.so:system/lib/libaudio.so \
    vendor/semc/urushi/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/semc/urushi/proprietary/etc/als_curve.conf:system/etc/als_curve.conf \
    vendor/semc/urushi/proprietary/etc/vold.fstab:system/etc/vold.fstab \
    vendor/semc/urushi/proprietary/etc/sensors.conf:system/etc/sensors.conf \
    vendor/semc/urushi/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
    vendor/semc/urushi/proprietary/bin/bq275xx_fwloader:system/bin/bq275xx_fwloader \
    vendor/semc/urushi/proprietary/bin/akmd8975:system/bin/akmd8975 \
    vendor/semc/urushi/proprietary/bin/chargemon:system/bin/chargemon \
    vendor/semc/urushi/proprietary/lib/libmiscta.so:system/lib/libmiscta.so \
    vendor/semc/urushi/proprietary/etc/firmware/touch_module_id_0x01.img:system/etc/firmware/touch_module_id_0x01.img \
    vendor/semc/urushi/proprietary/etc/firmware/touch_module_id_0x02.img:system/etc/firmware/touch_module_id_0x02.img \
    vendor/semc/urushi/proprietary/etc/firmware/touch_module_id_0x11.img:system/etc/firmware/touch_module_id_0x11.img
